### ISSUE TITLE
World Breakage when breaking a Pipe with contents on its way

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#1]
Breaking a pipe while a connected pipe is going to be sending an item to the broken pipe causes a world-breaking bug. Not sure what more help I can offer, but I do have [this crash report!] (http://pastebin.com/ByYYTw4p) Short story long: sent an item from a chest into one of my CrissCross machines, and it was sending them off just fine. But, after one had been sent off (but before arriving to my machine), I broke a pipe in the connection and got this once the item arrived to what used to be the meeting point of the now broken pipe.

**Comment by asiekierka** [comment]
Oh, that's silly.
