### ISSUE TITLE
Wire not providing block updates to attached blocks on state change

### ISSUE THREAD

**Issue by adudney** [asiekierka/CharsetMC#10]
Forge: 11.15.0.1609
Charset: 0.0.3-build 1

Edit: Upon further testing it appears to be whatever block the wire is placed on isn't getting an update, rather than just the block below it. Test 3 shows this.

Test 1:
![2015-12-06_22 12 50](https://cloud.githubusercontent.com/assets/246232/11619543/87074d8a-9c66-11e5-9f1e-a21796ad5c21.png)
![2015-12-06_22 12 54](https://cloud.githubusercontent.com/assets/246232/11619544/8708cc82-9c66-11e5-8363-8b2265437df3.png)
![2015-12-06_22 12 58](https://cloud.githubusercontent.com/assets/246232/11619542/8705fa52-9c66-11e5-9294-afb05a6a3bea.png)

Test 2:
![2015-12-06_22 15 41](https://cloud.githubusercontent.com/assets/246232/11619580/f192a9b0-9c66-11e5-921b-2085cfaacf57.png)
![2015-12-06_22 15 44](https://cloud.githubusercontent.com/assets/246232/11619582/f1a57b62-9c66-11e5-82c4-9ad0b3dab35b.png)
![2015-12-06_22 15 46](https://cloud.githubusercontent.com/assets/246232/11619581/f1a3daaa-9c66-11e5-8d51-9b6e3f74de51.png)

Test 3:
![2015-12-06_22 22 01](https://cloud.githubusercontent.com/assets/246232/11619656/cb6f6448-9c67-11e5-9879-246b5e86be89.png)
![2015-12-06_22 22 04](https://cloud.githubusercontent.com/assets/246232/11619658/cb7ff4ac-9c67-11e5-9fcb-8430f202a7f5.png)
![2015-12-06_22 22 09](https://cloud.githubusercontent.com/assets/246232/11619657/cb7f8c1a-9c67-11e5-979b-762f97e3fe5d.png)

**Comment by asiekierka** [comment]
https://github.com/asiekierka/CharsetMC/commit/7c119924a23452c604349fe81bb01ee8bed7c17b
