### ISSUE TITLE
Idea: Advanced Shifter

### ISSUE THREAD

**Issue by ToadsworthLP** [asiekierka/CharsetMC#100]
Let's get straight into the suggestion:

Advanced Shifter:
Makes items go fast. 2 times as fast as the regular speed, to be exact. Recipe:
G G G
G S G
G G G

G = Gold ingot, S = Shifter

Has higher push priority than regular Shifters, which means if something like this was built:
 
![20161224_101101](https://cloud.githubusercontent.com/assets/17457177/21466219/b5fbdab4-c9c1-11e6-8e22-67ae29997614.jpg)

(Had to use an image because GitHub doesn't care about whitespace)

= is a pipe, A is an Advanced Shifter and S is a regular one, if the Shifter and the Advanced Shifter was turned on, an item coming from the upper pipe would go to 3, but with 0.5x regular speed. If only the Advanced Shifter was turned on, it would also go to 3, but with 2x the regular speed. If only the regular Shifter was turned on, it would go to 1 with regular speed, and if none was turned on, it would go to 2. I hope this wasn't too complicated.
Should also have a nice golden texture.

PS: 100th issue. Yay🎉

**Comment by asiekierka** [comment]
* I am not particularly fond of tiering. It is, essentially, a deprecation of existing functionality in favour of a clear winner. I prefer variety.
* The speed is constant for a reason - 8 redstone ticks per pipe block makes for easy timing and I want to promote carts over pipes for long-distance transfer.
* Adding speed calculations to the Shifter logic would overcomplicate code greatly for no clear gameplay benefit. (Edit: In this particular case, you can re-arrange input pipes, output pipes and shifters to achieve similar end results.)
* Adding priorities to Shifters would take away from the simplistic, puzzle-like nature of the pipes, which I happen to greatly enjoy.

**Comment by ToadsworthLP** [comment]
Ok, thanks for the quick reply. Merry Christmas 🎄
