### ISSUE TITLE
Server crash on Minecraft 1.11.2 with Forge 2201

### ISSUE THREAD

**Issue by Soundtoxin** [asiekierka/CharsetMC#102]
Crash-report: http://sprunge.us/aTBc
Modlist: http://sprunge.us/hOOU

Crash happens both with and without foamfix, so I decided it's unrelated and just submitted the crash without foamfix. Crash didn't happen before adding Charset.

![1457039089424](https://cloud.githubusercontent.com/assets/3146494/21519982/97d7acaa-ccb6-11e6-87e6-e9c560828f4e.png)

**Comment by asiekierka** [comment]
Generally speaking, you do not need to remove FoamFix to report bugs to Charset. Since I develop FoamFix, I'm very well aware which parts of the Minecraft codebase it touches. Additionally, I tend to test with FoamFix myself.

Also, nice catch! Thanks.
