### ISSUE TITLE
Barrels Not Registered When Botania Is Active

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#103]
**Charset lib and storage versions:** [0.3.4](http://charset.asie.pl/changelog.html)
**Forge version:** [1.10.2-12.18.3.2185](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2185/forge-1.10.2-12.18.3.2185-changelog.txt)

**Notes from testing:**
I disabled Forestry, Botania, and Natural Pledge in my pack; the barrels got registered.
I enabled Forestry, and the barrels were still being registered.
I disabled Forestry and enabled Botania, and the barrels vanished

**List of JARs present:** [imgur/tvkWfB2](http://i.imgur.com/tvkWfB2.png)

**Comment by asiekierka** [comment]
I could not reproduce the issue with just Botania and Charset in my testing environment.

**Comment by asiekierka** [comment]
The code related to this has been rewritten probably almost entirely by now. For the time being, I'm closing it.
