### ISSUE TITLE
Stacking issue with scaffolds after breaking

### ISSUE THREAD

**Issue by sargunv** [asiekierka/CharsetMC#105]
1) Craft a set of scaffolds
2) Make a pillar of a few scaffolds (I did 4)
3) Break the bottom one
4) Pick them up

One of them does not stack with the rest. That one will drop as an oak scaffold regardless of the original scaffold type.

**Comment by asiekierka** [comment]
Thanks! I'll look into it.

**Comment by sargunv** [comment]
I made a quick video: https://youtu.be/IFuU3cGw4Ag?t=16s . The last 16 seconds are relevant to this bug.
