### ISSUE TITLE
Posters are on fire

### ISSUE THREAD

**Issue by sargunv** [asiekierka/CharsetMC#106]
For some reason, my posters are always on fire.

1) Craft a poster
2) Place a poster. It's burning. 
3) Make it look like an item. It's still burning.

I'm on 0.4.0-pre4

**Comment by asiekierka** [comment]
what

Screenshots?

**Comment by sargunv** [comment]
I made a quick video: https://youtu.be/IFuU3cGw4Ag . The first 16 seconds are relevant to this bug.
