### ISSUE TITLE
1.11 version not working because mcmultipart isn't update

### ISSUE THREAD

**Issue by MarcusElg** [asiekierka/CharsetMC#107]
It says that it wants forge 1.10

**Comment by asiekierka** [comment]
Could you elaborate? What Charset version, what 1.12 means, etc.?

**Comment by MarcusElg** [comment]
Latest version of charset. I ment 1.11, edited now.

**Comment by asiekierka** [comment]
Charset for 1.11+ never actually required MCMultiPart, though? I know it said it did, that was a mistake and has been fixed in 0.4.0-pre5+.
