### ISSUE TITLE
[1.10.2] Pipes refuse to connect to Tinker's Construct Tanks and Smeltery Drains

### ISSUE THREAD

**Issue by ToadsworthLP** [asiekierka/CharsetMC#108]
As already said in the title, the Pipes sadly don't connect to TiC stuff, for some reason. I'm using the latest TiC and Charset for 1.10.2, and I would love to pipe my molten metals between smelteries. Also, may we get a backport of the Carts module? And another random question: Is there a way to remove the poster?

**Comment by asiekierka** [comment]
>Pipes sadly don't connect to TiC stuff

That's a bug, thank you!

>backport

Not planned, sorry.

>And another random question: Is there a way to remove the poster?

I've noticed that myself as well! I'll look into it - thanks for reminding me.

**Comment by asiekierka** [comment]
After this fix, you should be able to sneak-left-click to break a poster.

**Comment by ToadsworthLP** [comment]
Do we need to compile it ourselves or will you provide a release?

**Comment by asiekierka** [comment]
I want to close the other 1.10.2-related issues first.

**Comment by ToadsworthLP** [comment]
Ok :D Thanks!
