### ISSUE TITLE
Breaking an empty barrel temporarily converts it into an oak barrel

### ISSUE THREAD

**Issue by sargunv** [asiekierka/CharsetMC#109]
1) Place a non-oak barrel
2) While it's empty, break it with an axe
    - It didn't break, just turned into an oak barrel
3) Put some dirt in, and it turns back to what it was

https://youtu.be/8JDOFN67FWc

0.4.0-pre4 on MC 1.11.2, Forge 13.21.0.2203

**Comment by asiekierka** [comment]
https://github.com/CharsetMC/Charset/commit/331f7103e9211e655b327e3a83b67771d35cf1f8
