### ISSUE TITLE
[Bug] Shifting fluids into a chest crashes the game

### ISSUE THREAD

**Issue by ToadsworthLP** [asiekierka/CharsetMC#113]
If you build something like this:
![2017-01-22_20 34 42](https://cloud.githubusercontent.com/assets/17457177/22185257/6ed70040-e0e2-11e6-9a14-2bbe9509e434.png)
The game crashes a few frames after flipping the lever, just when the water reaches the chest. When trying to load the world again after restarting Minecraft, it will crash instanly, effectively destroying the world. It also works when replacing the chest with anything that can store items (tested with Storage Drawer's drawer). This can only be fixed by removing the structure using MCEdit or something similar.

**Comment by asiekierka** [comment]
Fluid support in Charset is useless. I'll try to look into it soon, but it is disabled completely in 1.11+ for a reason.

**Comment by ToadsworthLP** [comment]
Ok, I hope to see it working again sometimes soon-ish :D

**Comment by asiekierka** [comment]
Just as a sidenote: In 1.10.2, for fluids, you need to explicitly shift them around - they won't auto-route.
