### ISSUE TITLE
[Suggestion] Colored shifters and pipes

### ISSUE THREAD

**Issue by ToadsworthLP** [asiekierka/CharsetMC#114]
I know you want to keep the pipe system easy and puzzle-like, but I'll try anyways:

Right-clicking a shifter with a dye item (lapis, ink sac, dandelion yellow,...) will change the (normally red) triangle's color and only push items that have been marked with that color. This can be done by piping them through pipes that have also been right clicked with a dye item (the pipe will also change it's color). For example, if you right click a pipe with cactus green, it will get a green hue. When piping an item through it, it also gets that slight color change (if that's too hard to implement you could also just render a colored frame around the item like Buildcraft) and will only get pushed by "green" and uncolored shifters.
I know you want to keep the pipe system simple, but, please, this would allow for some crazy contaptions like being able to know where an item comes from and shifting it into the right machine.
Also, backport to 1.10 because Tinker's isn't on 1.11? Nah, we won't get that anyways, but it was worth asking.

**Comment by asiekierka** [comment]
I was already considering colored item flow. The question is if it's worth the added complexity. I am aware of the contraptions - I added Lenses and Filters to BuildCraft to simplify its own color-coding system.

I'll leave this open because it is an idea I have been considering, and you have actually come up with more or less what I was planning myself.

**Comment by ToadsworthLP** [comment]
Well, that's a nice coincidence :D I hope this gets in the mod! On the point of added complexity: Newcomers won't be cofused because they don't even know about colored pipes and shifters, and if they want to use them, they can, but are not initially thrown into this new layer of complexity.
PS: Forgot that you originally implemented that system in BuildCraft! If I remember correctly you even did a video on your Youtube channel showcasing lenses and colored pipes.

**Comment by asiekierka** [comment]
I don't think I did a video on that, but I'm pretty sure I released a bunch of short videos on Gfycat.

**Comment by ToadsworthLP** [comment]
I checked, you showed an example in BuildCraft semi-weekly #0 and some more in BuildCraft Wheneverly #1. Also, I would love to see this kind of preview on your YouTube channel about Charset, you can call it Charset WhenIHaveTooMuchTimely ^^

**Comment by ToadsworthLP** [comment]
Also, will we get that in 1.10 too or do I have to wait for everything else (namely Tinkers, Progressive Automation, etc.) in my Modpack to update to 1.11 to enjoy these features?

**Comment by asiekierka** [comment]
@ToadsworthLP In 1.11, if anything. Sorry to have kept you waiting.

**Comment by ToadsworthLP** [comment]
No problem, then I'll just backport it myself, which shouldn't be too hard.

**Comment by asiekierka** [comment]
Won't be easy, as 1.11 pipes use MCMP2 and 1.10 pipes use MCMP1 - they're rather different. But sure!

**Comment by ToadsworthLP** [comment]
Ok, looks like I'll just mover over to 1.11 entirely, though I'll definitely miss some mods there. Why aren't more mods updating to 1.11 in the first place? I don't think it's a difficult one ._.

**Comment by exaskye** [comment]
1.11 is another tedious update, because code that worked in 1.10 will compile but not work properly in 1.11. You have to go through and verify all your inventory code is updated, and inventory code is usually a tangled mess.
