### ISSUE TITLE
NoteBlockManager breaking modded note blocks

### ISSUE THREAD

**Issue by Vexatos** [asiekierka/CharsetMC#115]
The [note block event is always being canceled](https://github.com/CharsetMC/Charset/blob/e75bf6d68281117c9c51f2ba7b95bc9073842382/src/main/java/pl/asie/charset/audio/note/NoteBlockManager.java#L57), no matter whether the block sending it is a Vanilla note block or not. There should be a check for that.

**Comment by SoniEx2** [comment]
GO FIX FORGE!

No really, go add NoteBlockEvent.GetInstrument to forge. It'll solve all (y)our issues.
