### ISSUE TITLE
NoteBetter support

### ISSUE THREAD

**Issue by SoniEx2** [asiekierka/CharsetMC#116]
Can you use NoteBetter API when NoteBetter is available? It'll be much better.

Actually, can you make NoteBetter a hard dependency? It'll be much better. Feel free to include NoteBetter as part of Charset if you want to. The mod is stable - the code has remained the same (except for a bugfix) since version 2.0, and works from 1.9 to 1.11.

**Comment by falkreon** [comment]
Instead, Soni, consider making your API good enough to be included into CapabilitiesCore or CommonCapabilities. If people think some kind of INotePlayer is an important abstraction, it'll naturally flow from these central capabilities providers out to mods like Charset.

**Comment by asiekierka** [comment]
>Can you use NoteBetter API when NoteBetter is available? It'll be much better.

If it gets enough adoption, sure!

>Actually, can you make NoteBetter a hard dependency?

Now that MCMultiPart 2 will not be a hard dependency on supporting mods, I don't plan to have any hard dependencies, period.

>The mod is stable - the code has remained the same (except for a bugfix)

That's not how that works.

**Comment by asiekierka** [comment]
@falkreon Not happening - NoteBetter is a bit more complicated than a capability.

**Comment by SoniEx2** [comment]
NoteBetter is like a total conversion mod that only affects noteblocks. The API is as simple as NoteBlockManager but 9000x more powerful.

**Comment by exaskye** [comment]
And you're asking a fully modular mod to create a hard dependency on it.

**Comment by SoniEx2** [comment]
No, I'm asking a fully modular mod to physically include the whole thing as part of the charset|audio module.

**Comment by exaskye** [comment]
...A fully modular mod, which is distinctly *not a total conversion*, and does not use ASM, to include a total conversion mod with ASM.

Do you seriously not understand how unreasonable your request is?

**Comment by SoniEx2** [comment]
I had to use ASM because Mojang is crap.

Well actually I needed a way to emulate japanese half-tick glitches, because the japanese asked me to. That's the only thing ASM is for. The API itself doesn't require ASM and I could even remove the whole "replace triggerNote with ASM" thing thanks to new Forge features. But then I lose the "compatible with a wide range of Minecraft versions" feature.

**Comment by asiekierka** [comment]
@unascribed Charset is actually aiming to lead towards a "total conversion", in one sense of the word (gameplay-wise), at some point.

@SoniEx2 This is still not happening at this point in time.
