### ISSUE TITLE
Wires don't power correctly when cornered

### ISSUE THREAD

**Issue by adudney** [asiekierka/CharsetMC#12]
Forge: 11.15.0.1609
Charset: 0.0.3-build 1

The state doesn't change on block update.

![2015-12-06_22 25 41](https://cloud.githubusercontent.com/assets/246232/11619752/b1287c86-9c68-11e5-86d2-231d72edc08e.png)
![2015-12-06_22 26 31](https://cloud.githubusercontent.com/assets/246232/11619755/b149a154-9c68-11e5-9f11-9503480db6d5.png)
![2015-12-06_22 28 01](https://cloud.githubusercontent.com/assets/246232/11619753/b1458ab0-9c68-11e5-9674-3ed56dc29c13.png)
![2015-12-06_22 28 11](https://cloud.githubusercontent.com/assets/246232/11619754/b147fe94-9c68-11e5-9c12-dc2941c57108.png)

**Comment by asiekierka** [comment]
https://github.com/asiekierka/CharsetMC/commit/7c119924a23452c604349fe81bb01ee8bed7c17b
