### ISSUE TITLE
Low quality, intended, limitation or bug? (1.10.2, Tape Drive)

### ISSUE THREAD

**Issue by DeadSix27** [asiekierka/CharsetMC#125]
Quality seems quite low, as if you cut down on the frequency range or bitrate (or both) very drastically (too much?), audio also seems to clip.

Is this an issue on my end, a intended behavior or a limitation of your implementation?

_(we talk quite a bit today, eh :) )_

**Comment by asiekierka** [comment]
Intended behaviour. The bitrate is effectively 48kbit/s, and it's using a simple codec to allow editing from computer mods in the future.

**Comment by DeadSix27** [comment]
Any chance for a configuration option to increase the quality somewhat?

**Comment by asiekierka** [comment]
Not at the moment, no.

**Comment by DeadSix27** [comment]
@asiekierka Was worth asking, thanks for your time anyway :)

**Comment by asiekierka** [comment]
No problem!
