### ISSUE TITLE
[1.11.2][0.4.0-beta10] Backpack configuration is still generating, even when removed

### ISSUE THREAD

**Issue by starg09** [asiekierka/CharsetMC#126]
Noticed this line on my newly-created config, at `storage.cfg`:

```
backpack {
    # Should backpacks be openable with a key binding? [default: true]
    B:enableOpenKeyBinding=true
}
```

Not sure if this is meant to integrate with Wearable Backpacks, or was just left there unintentionally. Anyway, better to let you know I guess 😄

**Comment by asiekierka** [comment]
Already fixed in the upcoming release.

It was left in unintentionally in 0.3.1.
