### ISSUE TITLE
Crash with Scaffolds

### ISSUE THREAD

**Issue by Vazkii** [asiekierka/CharsetMC#127]
http://puu.sh/uHmEr/2b4f7d7026.txt

Happened when just randomly spamming scaffolds in a new world. Furthermore, only the birch scaffolds show up in creative.

**Comment by asiekierka** [comment]
Outside of a development environment, only one scaffold type will show up, changing daily - you can change this behaviour in modules/lib.cfg, I believe.

**Comment by asiekierka** [comment]
https://github.com/CharsetMC/Charset/commit/065b0a5bc9b3928c8aec819447e2ce495b7648fa
