### ISSUE TITLE
Latest Charset (0.4.0) crashes instantly upon startup: wires module(??) can't find MCMultipart

### ISSUE THREAD

**Issue by MrEldritch** [asiekierka/CharsetMC#129]
I attempted to start a custom modpack up using the latest Charset and Forge. Surprisingly, it crashed before even fully loading. This issue persisted after I removed all other mods and set the garbage collector back to normal (I had been trying out G1GC). 

The log:
http://pastebin.com/mAuyNW2T

The reason given for the crash is 
"net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Charset (charset)
Caused by: java.lang.RuntimeException: The following mandatory dependencies were not met: lib.wires<-[mod:mcmultipart]"

Since AFAIK the wires module no longer even exists, and there is no separately distributed MCMultipart for 0.4.0 anyway, this is particularly puzzling. It also confuses me that this is occurring even when Charset is the only mod installed - surely, if other people were experiencing this, it would have already been noticed. Additionally, this occurs using both the latest Forge (#2255) and the most recent recommended Forge (#2228), so the sole element involved seems to be Charset.

**Comment by asiekierka** [comment]
I did not yet implement automatic module disabling based on what mods you don't have installed. I suppose you'll have to do it manually for the time being.

The wires module exists again, but as a *library* (used for example for audio cables).

I am aware of this problem but I didn't have a lot of time to look into it. Sorry.

**Comment by MrEldritch** [comment]
I do not know how to disable the modules, because modules.cfg and ids.cfg in the minecraft/config/charset folder are completely blank, 0 kB files. I think Charset crashes before it even has time to write anything to those files.

**Comment by asiekierka** [comment]
Oh, thanks.

**Comment by asiekierka** [comment]
Solved the part with modules.cfg not generating quickly enough, at least!
