### ISSUE TITLE
NPE Startup Crash with Storage Module

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#131]
**Mod version:** [0.4.0-pre10](https://charset.asie.pl/releases/0.4.0-pre10/changelog.txt)
**Forge version:** [1.11.2-13.20.0.2260](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2260/forge-1.11.2-13.20.0.2260-changelog.txt)

Crash during game startup, an NPE getting barrel type for `makeBarrel()`.

**Crash report:** [git.io/vS353](https://git.io/vS353)

**Comment by asiekierka** [comment]
Please try with Charset 0.4.0 @ https://asie.pl/Projects/Minecraft/Mods/Charset (with http://maven.amadornes.com/MCMultiPart2/MCMultiPart-exp/ )
