### ISSUE TITLE
Crash Report: Charset crashes when placing pipe next to shifter

### ISSUE THREAD

**Issue by MrEldritch** [asiekierka/CharsetMC#132]
https://pastebin.com/Q6GVd1FQ

I am using an instance containing only Charset, MCMultipart-Exp 2.0.0_17, and Forge #2260. (The crashlog is from an instance containing Chisels and Bits as well, but I removed it from the pack & the error persisted)

After some experimentation, the crash seems to be triggered when placing a pipe next to one that is attached to a Shifter, creating a scenario like this:

![image](https://cloud.githubusercontent.com/assets/6363834/24488198/e349ed76-14da-11e7-84d3-d48cfc44e372.png)

This occurs frequently, but not reliably - after relaunching the game after that crash, placing a pipe there again did not crash the game, but then laying down another Shifter and adding pipes did.

**Comment by asiekierka** [comment]
Should be fixed in MCMultiPart 2.0.0's stable release, whenever that comes out (soon!).
