### ISSUE TITLE
[1.12] Server NBT Issues

### ISSUE THREAD

**Issue by Kris1432** [asiekierka/CharsetMC#134]
Forge: 2382
Version: 0.4.2-pre1

Occurrence: When logging into a Dedicated Server, I get kicked and this message appears on the client: https://puu.sh/wwsg8.png and the following logs appear on the server.

The only 2 mods installed on the server are Charset and MCMultipart

Issue Logs:

https://pastebin.com/GKN3RWNa
https://pastebin.com/a6HBmd8d

**Comment by asiekierka** [comment]
Oh.

I'll look into it, thanks.
