### ISSUE TITLE
[1.12][0.4.2.9] Crash after placing bed

### ISSUE THREAD

**Issue by starg09** [asiekierka/CharsetMC#136]
[Report](https://gist.github.com/starg09/0d2ee88a3d8316f879da7d032135ac00)

I placed a white bed from vanilla, at that point lagged a bit. A red bottom half appeared, I may have clicked again, and then the game crashed and gave that report.

**Comment by cout970** [comment]
I had the same crash, but I just broke the bed, i didn't click on it
[Report](https://pastebin.com/jmAhaGre)
