### ISSUE TITLE
Crash on launch with latest CI build

### ISSUE THREAD

**Issue by shadowfacts** [asiekierka/CharsetMC#138]
Crash report: https://gist.github.com/shadowfacts/f311ba40f0c1b13f1dd6b6f10fd76076
Forge: 14.21.1.2387

That crash reports includes a couple other mods, but I've verified that it happens with just Charset.

**Comment by asiekierka** [comment]
Did you touch any configuration options in Charset?

**Comment by shadowfacts** [comment]
Nope, this is on the first launch with Charset added.

**Comment by asiekierka** [comment]
Huh. I've pushed a version just now, does that one work better?

**Comment by shadowfacts** [comment]
That seems to be fixed, but a [slightly different crash](https://gist.github.com/shadowfacts/41cbc7e439e800ea2eb4202646218f68) this time with the icon item.

**Comment by asiekierka** [comment]
It's weird because it looks like the event is called too... early? Huh. I'll look into it more.

**Comment by shadowfacts** [comment]
Yeah, that event would have to be firing before pre-init for the item to be null, but with the Forge registry changes, registry events are fired [immediately after](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/Loader.java#L604-L605) mod pre-init.
