### ISSUE TITLE
Add item detection API

### ISSUE THREAD

**Issue by rubensworks** [asiekierka/CharsetMC#14]
I need some way of reading which item is currently passing through a pipe.
Would it be possible to add a method like `getItem(...)` to `IItemInjectable` or some new interface?

Another minor thing: Would it be possible to add a method to the `IShifter` to enable it without requiring it to have a redstone signal? Or would this require too much changes to the code?

**Comment by asiekierka** [comment]
1. An official item detection method is coming (sometime after I finish gates, as the detection system could benefit from a good redstone backend) - I will look into an API method for it then.

2. The IShifter? It doesn't have to have a redstone signal. In fact, the code never checks if it has a redstone signal - isShifting() serves that purpose.

**Comment by asiekierka** [comment]
Tell me if this API works - I'm not exactly sure.

(For detectors, you most likely want to keep the EnumFacing as null and check the center.)

**Comment by rubensworks** [comment]
Ok, will check.

**Comment by rubensworks** [comment]
Seems to work just fine!
