### ISSUE TITLE
TESR Lighting Bug With Carry Tweak

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#145]
TESR's have an intermittent lighting issue when held using the Carry feature.

**Charset version:** [0.4.2.22](https://ci.elytradev.com/job/CharsetMC/job/Charset/job/1.12/22/changes)
**Forge version:** [1.12-14.21.1.2387](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387-changelog.txt)

---

**Example of lighting issue with a Quark chest (GIF):**

![GIF of rendering issue with a Quark chest](https://thumbs.gfycat.com/TintedWeirdBelugawhale-size_restricted.gif)

**Example of lighting issue with an enchantment table:**

![Image of rendering issue with an enchantment table 1](http://i.imgur.com/Caa6UOj.png)
![Image of rendering issue with an enchantment table 2](http://i.imgur.com/cUMNo5e.png)

**Comment by asiekierka** [comment]
TESRs in the carry tweak are actually a bit of a pain to fix the way I'm doing things now. I'll most likely have to invest in FakeWorlds.
