### ISSUE TITLE
Pocket crafting table deleting items

### ISSUE THREAD

**Issue by cout970** [asiekierka/CharsetMC#146]
When I grab the output of pocket crafting table, the rest of the crafting slots get deleted even if they had resources to craft an items several times.

Also after crafting wooden stairs, closing the gui, and open the inventory, the slots that previously where crafting slots are filled with planks, but when I try to grab them, they disapear (maybe it's a sever/client desync?)

**Comment by asiekierka** [comment]
So my dupe bug fix went a little too far. Hmm.

**Comment by asiekierka** [comment]
Reproduced, but the Pocket Crafting Table backend is a mess I no longer understand... it needs a rewrite.
