### ISSUE TITLE
Hopper Upgrade Barrel is a dupe glitch

### ISSUE THREAD

**Issue by Shadows-of-Fire** [asiekierka/CharsetMC#147]
Instead of returning the provided barrel stack with the Hopper upgrade as nbt, you instead get a barrel with the stacksize of the barrel stack in the grid, but with no hopper upgrade.

![image](https://user-images.githubusercontent.com/3682588/27938771-333bdb18-628e-11e7-8c5b-ca20695fa0b9.png)

**Comment by Shadows-of-Fire** [comment]
Upon further inspection, this recipe is not entirely broken.  It is only broken when the NBTTagList `"upgrades"` is not present on the itemstack.  The stack does not receive this tag upon crafting, only the two tags that determine its texture.  Placing the barrel in world and breaking it makes it recieve the `"upgrades"` tag, and then it can be crafted in to a Hopping Barrel.

**Comment by Shadows-of-Fire** [comment]
The stack size is still copied regardless.

**Comment by asiekierka** [comment]
Huh. I didn't spot that when testing, thanks

**Comment by asiekierka** [comment]
Thank you for the close inspection, though!
