### ISSUE TITLE
Carrying a cactus doesn't hurt the player in any way

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/CharsetMC#154]

**Comment by skyem123** [comment]
Random idea: how about only making the cactus give damage if you're not careful (hitting a wall, jumping, falling, etc), like you're gently holding it?

**Comment by exaskye** [comment]
Steve's hands are too blocky and large to be careful about holding a spiky cube. He'll get stabbed no matter what.

**Comment by skyem123** [comment]
Well... if I pick up I cactus with my bare hands, I'll be pricked but I won't bleed, but it'll hurt.
When I place it down it will also hurt. and then bleed.
