### ISSUE TITLE
Suggestion: Stained Glass Tanks

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#158]
The title is self-explanatory. I think it would fit in well with the "variant for every material" approach that Charset has for barrels, wrenches, scaffolding, etc.

**Comment by asiekierka** [comment]
I planned that for a while, but I'm not sure of the aesthetic aspect.

**Comment by asiekierka** [comment]
https://github.com/CharsetMC/Charset/commit/7424a49b3aab852c0faa717c36a133e92f07768e
