### ISSUE TITLE
Tweak: Disable Vanilla Style Tool is broken

### ISSUE THREAD

**Issue by 3TUSK** [asiekierka/CharsetMC#161]
Partial stacktrace:
````
Caused by: java.lang.UnsupportedOperationException: remove
	at java.util.Iterator.remove(Iterator.java:93)
	at pl.asie.charset.module.tweaks.remove.CharsetTweakRemoveVanillaTools.postInit(CharsetTweakRemoveVanillaTools.java:61)
	at pl.asie.charset.lib.loader.ModuleLoader.passEvent(ModuleLoader.java:524)
	... 49 more
````

Related code:
https://github.com/CharsetMC/Charset/blob/21761c0257076c55e7a91eecc25685c8f1b7b500/src/main/java/pl/asie/charset/module/tweaks/remove/CharsetTweakRemoveVanillaTools.java#L57-L65

One possible solution is `RegistryManager.ACTIVE.getRegistry(GameData.RECIPES).remove(recipe)`, but I am not exactly sure on this..

**Comment by ChloeDawn** [comment]
I personally wouldn't recommend removing recipes, regardless. It can cause multiple issues with mods that perform lookups on the registry name of the recipe; and with advancements that depend on the recipe. It is much safer to perform a registry replacement, much like you would with a block or item; replacing it with an empty IRecipe.

**Comment by ChloeDawn** [comment]
However if you do insist on direct removal, I believe the best approach is this (although I may be wrong):
```java
for (IRecipe recipe : ForgeRegistries.RECIPES.getValues()) {
	if (itemSet.contains(recipe.getRecipeOutput().getItem())) {
		((IForgeRegistryModifiable)ForgeRegistries.RECIPES).remove(ForgeRegistries.RECIPES.getKey(recipe));
		itemSet.remove(recipe.getRecipeOutput().getItem());
		ModCharset.logger.info("Disabled {} (removed recipe)", recipe.getRecipeOutput().getDisplayName());
	}
}
```

**Comment by 3TUSK** [comment]
The way I mentioned is what CraftTweaker implements their `recipes.remove()`. 

Replacing recipes is safer for sure; meanwhile it may lead to log spam (due to different ModContainer in context)
