### ISSUE TITLE
Tank crash when being filled from 3rd party source

### ISSUE THREAD

**Issue by Lothrazar** [asiekierka/CharsetMC#163]
https://pastebin.com/YVtMYsF6

Was reported to me https://github.com/PrinceOfAmber/Cyclic/issues/605

I have checked into my pipe and pump code, it seems ok and it works with many other tanks and fluid related machines.

**Comment by asiekierka** [comment]
Actually, that crash log implies you're trying to fill my tank with a null FluidStack. You shouldn't be doing that, but I added a check anyway as it saves some time if someone else tries to do so.

**Comment by Lothrazar** [comment]
Oh yeah my bad oops. Ill do a null check on my side to.  Since Item stacks are never null i must have assumed or gotten lazy.
