### ISSUE TITLE
Help! I deleted capitalthree and turned her into a minecart!

### ISSUE THREAD

**Issue by copygirl** [asiekierka/CharsetMC#166]
Apparently, with the block carry functionality, you can pick up a chest and place it into a player as if they were a minecart, replacing said player with a chest minecart and causing them to "despawn". The same appears to work for any entity.

**Comment by alexbobp** [comment]
Pros:
- forniphilia transformation
- source of iron
- ghost dropped items and other poltergiest action

Cons:
- glitchiness
- can't wander around as a minecart (minecart not synced to the player)
- can't pick up items
- not lore friendly

**Comment by ChloeDawn** [comment]
This is amazing

**Comment by skyem123** [comment]
You could have a special method where you turn things into Minecarts at a cost, so it can be balanced.

**Comment by KiriCattus** [comment]
How are things like this even possible xD I think it should be left in as an odd easter egg kinda thing now

**Comment by alexbobp** [comment]
Quick, somebody do a minecraft+charset speedrun where you drop a chest on the dragon to death before asie fixes

**Comment by liach** [comment]
what happened to the player then? is the player kicked or killed immediately?

**Comment by copygirl** [comment]
@liach: Removing a player from the world is really weird. You don't get kicked. You don't get sent any entity updates and entities can't see you. You can interact with the world in some ways. Like, charset block carry continues working, and you can still fire a bow.

**Comment by asiekierka** [comment]
I'm sorry.

**Comment by KiriCattus** [comment]
Awww no easter egg lol
