### ISSUE TITLE
Acacia chests transform into spruce chests on block carry

### ISSUE THREAD

**Issue by copygirl** [asiekierka/CharsetMC#167]
Also the orientation doesn't seem to be applied correctly..?

edit: My brain was in stream mode so I forgot to mention / test important details. Apologies!

**Comment by ChloeDawn** [comment]
Which mod are the chests from and what is the mod's version? What is your Forge version?

**Comment by exaskye** [comment]
Assuming she's talking about my modpack, the chests are from Quark. The versions are:

* Minecraft 1.12.2
* Forge 14.23.1.2559
* Quark 1.4-118
* Charset 0.5.0.88

(we play on a server, so these should be correct)

**Comment by asiekierka** [comment]
Could not reproduce, although I was using Quark 1.4-120 and Forge 2552.

Is there anything interesting in the log? Any coremods you think might be a culprit?

**Comment by asiekierka** [comment]
Wait. I just reproduced it. Whaaaat.

**Comment by ChloeDawn** [comment]
Do tile entities require special carry registration? Vazkii only registers the blocks, and stores the chest variant in tile NBT. See: [VariedChests.java#L76-L77](https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/decoration/feature/VariedChests.java#L76-L77) and [TileCustomChest.java](https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/decoration/tile/TileCustomChest.java)

**Comment by asiekierka** [comment]
@InsomniaKitten No.

Okay, I got it to reproduce, but *only* if you place the Quark chest next to another Quark chest.

**Comment by asiekierka** [comment]
Okay. I found the issue. It's related to a special hack implemented for vanilla chests, but Quark doesn't validate what ItemStack it receives in onBlockPlacedBy - well, nobody expects it to, so it's fine!

Working on a fix.
