### ISSUE TITLE
Any possibility on providing alternative recipe for tank, chisel and scaffold?

### ISSUE THREAD

**Issue by 3TUSK** [asiekierka/CharsetMC#168]
I have BuildCraft 7.99.13, Charset 0.5.0.94, Forestry 5.7.0.218 and IC2 2.8.30-ex112 in my pack that I am playing. Recipes of Charset's tank, chisel and scaffold conflict with [BuildCraft's tank](https://ftb.gamepedia.com/Tank_(BuildCraft)),  [Forestry's Grafter](https://ftb.gamepedia.com/Grafter) and [IC2's wood scaffold](https://ftb.gamepedia.com/Scaffold_(IndustrialCraft_2)), respectively.

For tank and scaffold, I can simply disable the one from Charset, as workaround; however, I can't do the same for Charset's chisel, because it's rather unique in my pack.

**Comment by asiekierka** [comment]
The conflicts with BuildCraft's tank and IC2's wood scaffold are not something I'm interested in fixing; the functionality also overlaps a fair bit and, honestly, you should probably choose one or the other. (I recommend the Charset tanks and scaffolds, obviously.)

As for the Grafter, that might actually get fixed upstream!

Can't you use CraftTweaker to remove the duplicates? Not sure if you can use it to *add* recipes; you might need to modify the JAR, as the Charset recipes have a custom JSON format... you can also make your own mod and copy Charset's _factories.json.

**Comment by 3TUSK** [comment]
> Can't you use CraftTweaker to remove the duplicates?

Surely I could; however, I consider my pack as too small to let things like CraftTweaker fits in. Might just write a small mod to do some conversion and wait for Datapack becoming a thing...

**Comment by asiekierka** [comment]
Yes, datapacks will work *amazingly* with Charset.

**Comment by asiekierka** [comment]
As for the chisel, it appears I already changed the recipe a few builds after the one you're using! But I might change it again.

**Comment by asiekierka** [comment]
And, with the latest build, the chisel recipe is fixed.

**Comment by 3TUSK** [comment]
> Just a side-note: Forestry's Workbench can let you specify the output when one recipe matches multiple outputs.
