### ISSUE TITLE
[1.12.2] Audio Module crashes client and server upon world load

### ISSUE THREAD

**Issue by DeadSix27** [asiekierka/CharsetMC#171]
Error looked like it misses a storage module (e.g the tank or barrel one), but no other deps. are listed on curse.

Crash log: https://gist.github.com/DeadSix27/5867532c5f75d4950b145c8394908eb5

EDIT: Actually this also happens on clients and its not on start, its on world loading.

**Comment by asiekierka** [comment]
Yep, you've found a bug!

**Comment by DeadSix27** [comment]
@asiekierka \o/ don't we all love bugs. :P

**Comment by Gelles** [comment]
Looks like I found the same bug, but only with Charset Lib loaded (initially had Lib, Barrels, and Rails). It crashes on the World Selection GUI.

Curiously, I can't reproduce this on a fresh install with just latest Forge (2583) and the Charset stuff. 

Here's my crash log: https://pastebin.com/QzUbyuEj

**Comment by asiekierka** [comment]
Yes, I'm aware, I'm working on this.

**Comment by asiekierka** [comment]
A fix should be out on CurseForge within ~3 hours. The workaround is to install StorageBarrels, as this is the module with a broken dependency.
