### ISSUE TITLE
All languages files other than English are not included in build artifacts

### ISSUE THREAD

**Issue by 3TUSK** [asiekierka/CharsetMC#172]
I was watching a Chinese player's let's play series yesterday and noticed that he is using Charset 0.5.0.109 which does not have Chinese localization, even though the game language was set so. 

Then I went to check the artifact I am using (from elytra CI), and noticed that there is only `en_us.lang` in the artifact. Is that intended?

**Comment by asiekierka** [comment]
Apparently not. Thanks for noticing! This was a Jenkins configuration issue. 0.5.0.120+ should be fine.

**Comment by asiekierka** [comment]
^ That one was meant to be #173.
