### ISSUE TITLE
[1.12.2] Charset Audio, record player crashes client during upload

### ISSUE THREAD

**Issue by DeadSix27** [asiekierka/CharsetMC#173]
During upload of a audio file I crash with:
java.lang.NullPointerException: Ticking screen

Full log: https://gist.github.com/DeadSix27/bccdd72421dab7e615a4baf10ad94235

Not sure if this is fixed in dev yet, I have not tried building the mod from source yet to find out.

**Comment by asiekierka** [comment]
https://github.com/CharsetMC/Charset/commit/36e9d28ba76e5de0a561a6d4f888be899300d188

**Comment by DeadSix27** [comment]
@asiekierka Thank you :)
