### ISSUE TITLE
java.lang.NoClassDefFoundError: pl/asie/charset/lib/wires/BlockWire

### ISSUE THREAD

**Issue by LemmaEOF** [asiekierka/CharsetMC#174]
I probably messed the config up somehow, but it's crashing bc it can't find BlockWire

Charset ver. 0.5.0.118 (from CI), MC ver. 1.12.2, Forge ver. 14.23.1.2584

[crash](https://github.com/CharsetMC/Charset/files/1609506/crash-2018-01-06_20.51.18-client.txt)

**Comment by LemmaEOF** [comment]
lib.wires is enabled in config, so I'm not sure what's going on. I might need charset patches, so I'll need to build that for myself since the CI is down

**Comment by exaskye** [comment]
Try installing MCMultiPart.

**Comment by LemmaEOF** [comment]
It was that easy. I'm good at creating modpacks.
(side-note: why the hell isn't mcmultipart in my openskies pack anyway it's a dependency of chisels & bits I'll fix that when the servers stop being a fuck)
