### ISSUE TITLE
Crash java.lang.StringIndexOutOfBoundsException: String index out of range: 0 

### ISSUE THREAD

**Issue by LemmaEOF** [asiekierka/CharsetMC#175]
the Charset SplashTextHandler gives a StringIndexOutOfBoundsException when reaching the main title screen.

Charset 0.5.0.118(from CI), Minecraft 1.12.2, Forge 14.23.1.2584, CharsetPatches 0.1.0 (CharsetPatches 0.1.1 crashes the game before the game wrapper even appears, and gives no crash log)
[crash-2018-01-06_21.35.26-client.txt](https://github.com/CharsetMC/Charset/files/1609522/crash-2018-01-06_21.35.26-client.txt)

**Comment by asiekierka** [comment]
Well, yes, CharsetPatches 0.1.1 needs a newer version of Charset.

**Comment by LemmaEOF** [comment]
I guess I'll grab it once the CI is back up.

**Comment by LemmaEOF** [comment]
Nope, still happening. Charset 01.0.124 (from CI), Minecraft 1.12, Forge 14.23.1.2584, no CharsetPatches (because CharsetPatches 0.1.1 _still_ crashes the game before the game window appears, with no logged reason why)
[crash-2018-01-07_13.46.45-client.txt](https://github.com/CharsetMC/Charset/files/1610232/crash-2018-01-07_13.46.45-client.txt)

**Comment by ChloeDawn** [comment]
@asiekierka why do you have two identical classes for this? this is the issue class here that needs fixing: [SplashTextHandler.java#L53](https://github.com/CharsetMC/Charset/blob/1.12/src/main/java/pl/asie/charset/lib/handlers/SplashTextHandler.java#L53)

**Comment by asiekierka** [comment]
@InsomniaKitten good question
