### ISSUE TITLE
[Suggestion] Add fluid cells

### ISSUE THREAD

**Issue by Skillotic0703** [asiekierka/CharsetMC#180]
I think fluid cells are a really neat feature. It would be very cool to be able to use fluid cells without needing Forestry, IC2, TechReborn or ThermalExpansion. Thank you in advance.

**Comment by asiekierka** [comment]
I think this is out of scope for Charset - for transporting large quantities of items and fluids, we much prefer using the Block Carrying tweak and carrying entire blocks around, or perhaps putting them into a minecart.

However, Tanks cannot be put in Minecarts yet. That (and Record Players) should be fixed. We also need a way to create trains.
