### ISSUE TITLE
NPE during teleport (or death)

### ISSUE THREAD

**Issue by DeadSix27** [asiekierka/CharsetMC#186]
log: https://gist.github.com/DeadSix27/6fd0ce069043ff7ce28c69ec9cc41c40

Offtopic: How does one build your mod themselves? Default gradlew build only builds a single jar which at least last time I tried didn't include the audio module etc. (I built of the 1.12 branch, the package.sh seems to only add license headers/notice so I didn't use that (since its private use anyway)

**Comment by asiekierka** [comment]
@DeadSix27 It does include the audio module. However, you need to pre-configure the mod - by default, only STABLE modules are enabled; check charset.cfg and modules.cfg.

**Comment by asiekierka** [comment]
I am aware of this bug, I unfortunately don't have time to fix it now - I'm leaving soon and will only have access to my development machine on Saturday (laptop's not working anymore).

**Comment by DeadSix27** [comment]
> I unfortunately don't have time to fix it now

No hurry :)
> It does include the audio module. However, you need to pre-configure the mod

Oh makes sense, thanks for the info !
