### ISSUE TITLE
Carry Tweak Entity Interaction NPE 

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#187]
I sneak+middle-clicked a Roots 2 deer; the game promptly choked and died. Can confirm this happens with vanilla mobs too; tested with a Squid.

**Mod version:** [0.5.0.140](https://ci.elytradev.com/job/CharsetMC/job/Charset/job/1.12/140/)
**Stacktrace:** [pastebin/7ja1dtm7](https://pastebin.com/raw/7ja1dtm7)

**Comment by copygirl** [comment]
The deer / squid did not turn into a minecart? Awwww.
