### ISSUE TITLE
Color Unification CTM Conflict

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#188]
When the color unification tweak is enabled, it conflicts with CTM, and seems to break texture paths for the CTM texture sprites. This can be produced using [the official connected textures pack](https://minecraft.curseforge.com/projects/ctp), looking at stained glass.

**Mod version:** [0.5.0.145](https://ci.elytradev.com/job/CharsetMC/job/Charset/job/1.12/145)
**CTM version:** [0.2.3.12](https://minecraft.curseforge.com/projects/ctm/files/2519601)

**With color unification:**

![with_color_unification](https://i.imgur.com/ZiE8iKd.png)

**Without color unification:** 

![without_color_unification](https://i.imgur.com/O98B28C.png)

**Comment by asiekierka** [comment]
```
asie | I add in my sprites using .setTextureEntry, but the ASM hook for TextureCollectedEvent only listens to .registerSprite  
asie | therefore, if glass_red is added using setTextureEntry, the TextureCollectedEvent will never fire and the texture for glass_red_ctm will never be registered 
asie | and *thus* the CTM texture will become a missingno 
```

You're going to have to bill me for dealing with CTM/Chisel's hacks next time. Can'tfix.
