### ISSUE TITLE
Dedicated server crash

### ISSUE THREAD

**Issue by JoeJoeTV** [asiekierka/CharsetMC#189]
When i try to start a dedicated forge server (FORGE VERSION:14.23.1.2600) it crashes on initialization.
Here is the crash report: https://pastebin.com/twnaTTDs
Charset Version: 0.5.0.141 and up

**Comment by asiekierka** [comment]
thanks mojang

Workarounds:

1. Disable the Charset Tablet module
2. Put a recent Apache httpclient JAR into mods/ on the server side

**Comment by JoeJoeTV** [comment]
where can i get the apache httpclient jar?

**Comment by 3TUSK** [comment]
https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.4

> But seriously, does that TabletAPI.INSTANCE need to do *anything* on server side? IMHO a book/guide/tablet/manual/[insert other form] should only process its text stuff on client side.

**Comment by asiekierka** [comment]
@3TUSK I was considering adding support for extracting Tablet information to OpenComputers, but this delays my plans for that a bit.
