### ISSUE TITLE
Torches Drop With Meta 0 From Block Update

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#194]
When a torch is broken due to a block update such as their required solid face being removed, they drop as a black beam torch (meta 0).

**Mod version:** [0.5.0.163](https://ci.elytradev.com/job/CharsetMC/job/Charset/job/1.12/163/)

**Recording of issue:**

![recording](https://thumbs.gfycat.com/HotSociableKakarikis-size_restricted.gif)

**Comment by asiekierka** [comment]
Yeah, I think that's a leftover from when they were light jars.

Beam torches in particular are still being evaluated.
