### ISSUE TITLE
[1.10.2]Ticking screen when trying to upload an audio to a remote server.

### ISSUE THREAD

**Issue by Yesterday17** [asiekierka/CharsetMC#195]
The latest stable version 0.3.8 crashes with ticking screen when trying to update audio to a remote server. Similiar to #173 , but crashes at pl.asie.charset.audio.storage.DataStorageImpl.initialize(DataStorageImpl.java:70)

Single player Mode works well. Only occurs in MultiPlayer.

Crash Report [here](https://pastebin.com/y8TXRCXb).

**Comment by asiekierka** [comment]
Yes, it's the exact same bug, though I didn't realize it also affected 1.10.

**Comment by asiekierka** [comment]
http://asie.pl/files/Charset-0.3.9-test1.jar Does this work right?

**Comment by Yesterday17** [comment]
@asiekierka It works well when i tested it with a server and a client on the same computer.

**Comment by asiekierka** [comment]
https://github.com/CharsetMC/Charset/commit/e6ac14e3ddcb8fc71930b6620558d3f680e2c4be
