### ISSUE TITLE
[Suggestion] Coumputercraft compatibility

### ISSUE THREAD

**Issue by JoeJoeTV** [asiekierka/CharsetMC#196]
Mybe add Computercraft compatability because Computercraft supports 1.12.2 too now.

**Comment by asiekierka** [comment]
The amount of code to maintain is roughly on par with OpenComputers, but as I do not use ComputerCraft myself it is not likely to happen soon.

**Comment by JoeJoeTV** [comment]
Ok that's understandable. I just asked because i sometimes don' t understand OpenComputers and found Computercraft easier.

**Comment by asiekierka** [comment]
I know ComputerCraft is more approachable as a mod. It's just that I'm unlikely to take on a maintenance burden for something I won't ever use myself.

However, I'm not ruling this out, and someone else might come and contribute the necessary code - so I'll leave this open for now.

**Comment by JoeJoeTV** [comment]
Ok, thank you
