### ISSUE TITLE
Cauldrons containing fluids other than water consume empty bottles

### ISSUE THREAD

**Issue by stohun01** [asiekierka/CharsetMC#199]
- Using a glass bottle on a cauldron filled with water fills a single bottle instead of the normal 3.
- Using a bottle on a cauldron containing lava or dyed water consumes the bottle with no change to the cauldron.

**Comment by asiekierka** [comment]
~~So a glass bottle, which stores 333.(3)mB of water, can fill 1000mB of water?~~ Nevermind, I can't read.

These do sound like bugs. I'll look into them ASAP.

**Comment by stohun01** [comment]
It takes 3 bottles to fill a cauldron but only 1 to empty it.

**Comment by asiekierka** [comment]
That made it clearer to me, thanks.

Expect a fix on Thursday-Friday, I might not be able to do one earlier.

**Comment by stohun01** [comment]
Thanks, no rush. Also is it possible to add dispenser interactions to cauldrons? like being filled via a bucket or adding dyes.

**Comment by asiekierka** [comment]
Adding dyes should already work, provided you drop the dye item into the cauldron. (It's not ideal, I know)

As for filling via a bucket, I'll consider it - perhaps more globally, as to allow filling tanks/etc. But I am not sure.

**Comment by stohun01** [comment]
Could dropping a full bucket into an empty cauldron be an option. A hopper underneath would collect the empty bucket.

**Comment by stohun01** [comment]
Also (sorry) the comparator output should probably be raised to 8 when full instead of 3

**Comment by asiekierka** [comment]
>It takes 3 bottles to fill a cauldron but only 1 to empty it.

Can't reproduce, sorry. Works fine for me. Any other hints which might help me reproduce it?

>Using a bottle on a cauldron containing lava or dyed water consumes the bottle with no change to the cauldron.

Also can't reproduce on latest version.

>Also (sorry) the comparator output should probably be raised to 8 when full instead of 3

Not right now. We're aiming for vanilla compatibility first.

**Comment by stohun01** [comment]
I'm not sure what is causing it. Another weird thing is if you have a stack of 8 water bottles and right click the cauldron it fills 1/3 with water and you're left with only 1 empty bottle.
[Mod list](https://pastebin.com/1k613NhD)

**Comment by asiekierka** [comment]
Can you reproduce this with just Charset, by the way?

**Comment by asiekierka** [comment]
Note that this was a CharsetLib bug - CharsetCrafting does not need an update.
