### ISSUE TITLE
Unable to make custom barrels with non-vanilla blocks via CraftTweaker

### ISSUE THREAD

**Issue by stohun01** [asiekierka/CharsetMC#202]
Recipes can be made with CT for barrels with custom textures, however it seems to only work for vanilla blocks. this line works:
`recipes.addShapeless(<charset:barrel>.withTag({log: "minecraft:stone;0", slab: "minecraft:stone;0"}),[<minecraft:stone>]);`

but this line will output a default oak barrel with the defined tag:
`recipes.addShapeless(<charset:barrel>.withTag({log: "quark:iron_plate;0", slab: "quark:iron_plate;0"}),[<quark:iron_plate>]);`

**Comment by asiekierka** [comment]
Try a non-vanilla _block_ in the tag, as the barrel reuses the block's textures - which won't work for items.

**Comment by stohun01** [comment]
The iron plate from quark is a block.

**Comment by asiekierka** [comment]
Huh. Sorry, was thinking of IC2.

I have a theory - Charset has a builtin "item material" system, and - as the Iron Plate is never registered to it - it might not be willing to use it. This might be a tougher issue to solve than I initially thought - I'll get back to you on that, but it will take some time.

**Comment by stohun01** [comment]
no worries.

**Comment by asiekierka** [comment]
![](https://img.asie.pl/m7c1)

The stopgap solution? is implementing hooks for the material registry to Charset's CraftTweaker integration.

    mods.charset.MaterialRegistry.registerTypes(<quark:iron_plate>, "plate", "block", "iron");

If you need tips on what to use for each block as types, set enableDebugInfo=true in module/lib.cfg and consult the then-created charsetItemMaterials.txt - or study the source code.

**Comment by asiekierka** [comment]
It's not pushed yet, though, so it won't work just now - it should be out within 24 hours, however.

**Comment by asiekierka** [comment]
I guess it's solved.
