### ISSUE TITLE
Charset StorageBarrels being loaded but not registered

### ISSUE THREAD

**Issue by Xaikii** [asiekierka/CharsetMC#207]
I am using I think the whole Charset Set and everything is loading properly except the Hopping Infinite Bedrock Barrel
The Mod is in my folder, it appears in the Logs therefore it **is** found 

But for some reasons I cant find any Barrels anymore except the 
And yes I checked the configs

Versions:
Charset-StorageBarrels-0.5.0.190(also tried Charset-StorageBarrels-0.5.0.199)
Charset-Lib-0.5.0.208
CharsetPatches-0.1.4
Charset-Tweaks-0.5.0.199
Forge 14.23.2.2635

I think the other Mods cant cause this

[Lib Config](https://hastebin.com/oriwupacib.bash)
[Modules Config](https://hastebin.com/kabadevico.coffeescript)
[StorageBarrels Config](https://hastebin.com/oyumucurub.bash)

**Comment by Xaikii** [comment]
Reloading the Configs doesn't help btw.

**Comment by asiekierka** [comment]
Always use the latest versions of each Charset module.

>I think the other Mods cant cause this

Don't assume things. Send up the whole mod list.
