### ISSUE TITLE
[Charset Audio Suggestion] Add function to OpenComputers support for resetting player arm position.

### ISSUE THREAD

**Issue by ofseaandstars** [asiekierka/CharsetMC#209]
It would be great if there was a function within the OpenComputers support to reset the player arm to default (thus allowing tracks to be started and reset by computers).

I imagine just a `.resetPosition()` function would be good enough.

**Comment by asiekierka** [comment]
Doesn't .stop() do that?

**Comment by ofseaandstars** [comment]
I can't see `.stop()` in the component list (using `=component.record_player` to list all of the function, `.stop()` doesn't appear in that list.

But yes, it does work.

**Comment by ofseaandstars** [comment]
I think this is an OpenComputers display issue, not a problem with your mod. Thanks for your help :)

**Comment by asiekierka** [comment]
The built-in Lua interpreter doesn't show whole tables, just parts of them unless they're very small. So no, that command won't list all of the functions.
