### ISSUE TITLE
[Compatibility idea] Computronics' audio cable usable with record players

### ISSUE THREAD

**Issue by Alessandro404** [asiekierka/CharsetMC#211]
I find the record player of charset: audio a pretty good alternative to computronics tapes, when I want to use .mp3.
Why not using the same cables if I have both in my base? I dislike multipart, so having another option could be good.

**Comment by asiekierka** [comment]
>I dislike multipart

Why?

>so having another option could be good.

Computronics at least *used to* support the same cables. Not sure what's the situation like now. @Vexatos ?

**Comment by Vexatos** [comment]
As far as I know, Computronics does support Charset wires just fine. Maybe I forgot to re-add it in 1.12. But pretty sure I didn't.

**Comment by Alessandro404** [comment]
My problem is the opposite. Computronics audio cables doesn't attach to the block

![2018-04-01_18 42 18](https://user-images.githubusercontent.com/8747581/38175415-6d89cd62-35dc-11e8-93b8-993ba7e4c97e.png)

**Comment by Vexatos** [comment]
That will not work unless charset implements Computronics' audio API. Charset wires should just work with both.

**Comment by asiekierka** [comment]
Just use Charset wires.

**Comment by asiekierka** [comment]
You mentioned disliking multiparts, that's fair; I'll open up a pertaining issue.
