### ISSUE TITLE
charset immersion, bunch of errors

### ISSUE THREAD

**Issue by walker-dev** [asiekierka/CharsetMC#212]
placing/breaking items in the world causing me to not be able to do anything else.
it does stack but it the first items seems to disapear the moment i place it.
no client log,
but server registers -> [latest.log](https://gist.githubusercontent.com/boosterdev/dd4e72fc1cec8ea75ec5254c0bab2447/raw/)

**Comment by asiekierka** [comment]
oh

**Comment by asiekierka** [comment]
https://github.com/CharsetMC/Charset/commit/07218359aa1b05304d506995429f7d759c8a9649
