### ISSUE TITLE
Charset Immershun

### ISSUE THREAD

**Issue by Fortist** [asiekierka/CharsetMC#213]
Holding an ingot ignores anything right-clickable and starts a stack in front of it.

**Comment by asiekierka** [comment]
Hah. I'm not sure if I can do much about this. We'll see, I guess.

**Comment by walker-dev** [comment]
Key combo required for stacking might be an option,

**Comment by ChloeDawn** [comment]
Requiring sneaking would resolve this issue

**Comment by asiekierka** [comment]
Actually, I'm going to try something much nastier. Let me know if it works out.

https://ci.elytradev.com/job/CharsetMC/job/Charset/job/1.12/218/

What this magnificent hack will do is:

* if you're placing on a simple block (grass, stone, wood, etc. - you get the idea), it will act as it does now (right-click to place one, sneak-click to place stack)
* if you're placing on a block which does something when right-clicked (furnaces, chests, etc. - you get the idea), it will place one on sneak-click and forward to the machine on right-click.

Does this make sense?

**Comment by asiekierka** [comment]
Actually. Another idea I've had. Simpler.

Make it so that you can only place ingots by right-clicking the top face of a solid block, or by right-clicking another already placed ingot.

The two could possibly be combined to create something non-intrusive.

**Comment by HarrisFauntleroy** [comment]
Is it possible to automate the placement of ingots into piles like you could with the stacks on stacks mod?

**Comment by asiekierka** [comment]
Be more specific, please. I haven't ever used StacksOnStacks, to be honest, and a description will help me figure out what you're after exactly.

**Comment by HarrisFauntleroy** [comment]
The ingot piles. is there a way to make their creation automatic, like a dispenser, when given ingots will only place one, if it could create a full pile, and keep going upwards as a player placed pile would, you could pipe ingots into dispensers for automated storage of stacks of ingots. Would add to their usefulness and take them beyond almost primarily cosmetic storage

**Comment by asiekierka** [comment]
I could add a dispenser behaviour like that  probably.

**Comment by copygirl** [comment]
I don't suppose it's possible to add a dispenser behavior that, when empty, will *pick up* an item from the stack? Presumably to be pulled out by a hopper right away.
