### ISSUE TITLE
[Client Crash] Tesselating block model by placing RS Latch

### ISSUE THREAD

**Issue by Sewef** [asiekierka/CharsetMC#215]
Hello,
I was building my pulse extender with a Timer (Dark Utilities) and a RS Latch Gate (Simple Logic).
I placed the RS Latch Gate next to the 20-tick Timer, and I crashed.

Here the crash report : https://pastebin.com/Rpd5D5Ws

Edit : looks like a CTM compatibility problem. Got a similar issue [there](https://github.com/Chisel-Team/ConnectedTexturesMod/issues/51)

Edit2 : without chiseled blocks, but next to a Connected Block (Pressure Chamber from Pneumaticcraft)
https://pastebin.com/TXvS3BWX
Not the same error, but maybe related

**Comment by asiekierka** [comment]
Nope! This one's totally my fault.
