### ISSUE TITLE
cauldron crafting destroys items

### ISSUE THREAD

**Issue by xkforce** [asiekierka/CharsetMC#216]
If you right click a cauldron with any item, it just destroys it rather than use it as a crafting ingredient.  Which means that none of the example crafting recipes work.  This is why in issue https://github.com/CharsetMC/Charset/issues/199 these glass bottles are being consumed but not changing the level of the fluid... because they're being destroyed like every other item that is used on cauldrons.

**Comment by asiekierka** [comment]
Bingo, thanks.

**Comment by asiekierka** [comment]
Well. Not exactly "bingo". But it got me on the right path.

Either way, duplicate of https://github.com/CharsetMC/Charset/issues/199 - but with useful info.
