### ISSUE TITLE
Crash with hopping barrles

### ISSUE THREAD

**Issue by Yarden-zamir** [asiekierka/CharsetMC#219]
I put a hopping barrel on top of a normal barrel, then I put a logistic requester fram from pneumaticraft on the top barrel and when I put a stack of logs in it I crashed
[2018-04-13-1.log](https://github.com/CharsetMC/Charset/files/1905456/2018-04-13-1.log)

**Comment by asiekierka** [comment]
That's not the latest version of the mod! It was fixed just one build after it - in builds 217 and above.

**Comment by Yarden-zamir** [comment]
Oh, sorry my bad
