### ISSUE TITLE
Potion support in Cauldrons

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/CharsetMC#220]
- [x] Add potion Fluid
- [x] Extract potion fluid from bottles
- [x] Wrap IFluidContainerItem around the glass bottle

**Comment by copygirl** [comment]
I think Immersive Engineering also has potion fluids. Any plans on the fluids being interchangable or using pre-existing potion fluids if another mod already adds them?

Also, how are potions crafted, then? Do they take time to brew? Where would the blaze powder come in, if at all? I just had the the idea that maybe you could put a special blaze powder fueled fire below. Throw one in a fire and it turns into a semi-permanent fire source that only decreases as potions are being brewed in a cauldron on top of it..?

**Comment by asiekierka** [comment]
Doubt it, as storing arbitrary potions requires NBT data, and that cannot be reasonably interchanged as mods can break their internal NBT storage at any time.

Crafting of potions in Cauldrons, or brewing them in Cauldrons, is outside the scope of this issue. It's just about storage at this point, so that I can make Glass Bottles (which use the same Item for water and potions) a Forge-compatible IFluidContainer.

**Comment by asiekierka** [comment]
They are *supported* now, but can't be brewed in the Cauldron. Progress, slowly...
