### ISSUE TITLE
Cauldrons break instantly

### ISSUE THREAD

**Issue by build2stone** [asiekierka/CharsetMC#222]
Seems a bit obvious, but i couldn't find any issues referencing it.

Pretty much the title. As far as i can tell, any item will work for this, even bare hands. If a pickaxe is used the cauldron drops as an item, and the pickaxe doesn't lose durability.

Tested using Charset-0.5.0.234-full and forge-14.23.3.2669

**Comment by asiekierka** [comment]
Oh, that's an issue I make all the time. Insufficient Survival Mode testing. I'll fix it today.
