### ISSUE TITLE
Charset Immersion creates invisible blocks when stack placing fails

### ISSUE THREAD

**Issue by build2stone** [asiekierka/CharsetMC#226]
When trying to place a stack on an invalid block (for example a transparent one), instead of nothing happening, an invisible block with no bounding box is placed.

Tested using Charset-0.5.0.241-full and forge-14.23.3.2670

**Comment by asiekierka** [comment]
Does rejoining the world make the block disappear? (That is, is the block a client-side artifact, or is it actually on the server too?)

**Comment by build2stone** [comment]
Just tried, rejoining doesn't make it disappear.
