### ISSUE TITLE
Dupe/item disappearance bug with Bottles and Tanks

### ISSUE THREAD

**Issue by DylanGK** [asiekierka/CharsetMC#227]
There is a weird interaction between Glass Bottles and Tanks when transferring fluids.  

How to replicate:
- Use any sort of filled Bottle containing a fluid (I am currently using the Rustic ones, various brews and Olive Oil) and right-click a Tank a bunch of times in a row.
- Watch your inventory.

**Comment by asiekierka** [comment]
>Watch your inventory.

Works as expected: drains Bottle in survival mode, does not drain bottle in Creative mode.

**Comment by asiekierka** [comment]
Closing due to lack of response.
