### ISSUE TITLE
In-world tooltip of cauldron w/ dyed water is hard to read under some circumstances 

### ISSUE THREAD

**Issue by 3TUSK** [asiekierka/CharsetMC#228]
![screen shot 2018-04-23 at 20 27 33](https://user-images.githubusercontent.com/9113033/39164576-efa9e5ac-4734-11e8-99b2-6f2ff8b6b398.png)

Environment:
* Forge 14.23.3.2673;
* Charset 0.5.0.244, profile EXPERIMENTAL;
* FoamFix 0.9.8-1.12.2-anarchy;
* World generation is superflat with "Redstone Ready" default template.

**Comment by asiekierka** [comment]
Strange. Does it always look dim like that?

**Comment by 3TUSK** [comment]
![2018-04-24_09 38 56](https://user-images.githubusercontent.com/9113033/39201271-57fa00ce-47a3-11e8-9a22-675511955637.png)

This time I only have:
 * BetterFps-1.4.8
 * Charset-0.5.0.244
 * foamfix-0.9.8-1.12.2-anarchy
 * jei_1.12.2-4.9.1.168

Looks better. Some weird interference going on? Do you need the full mod list used for the first screenshot?

**Comment by 3TUSK** [comment]
Strangely, I can't replicate the issue with the same mod setup and the same world...

**Comment by asiekierka** [comment]
It's an OpenGL context issue. It will only happen randomly, probably with a combination of specific position in-world, specific items held and specific blocks visible...

**Comment by 3TUSK** [comment]
Would it be worth sharing my hardware info?

**Comment by asiekierka** [comment]
No, it's related to the order in which certain blocks (particularly tile entities) from other mods render. Can also be a coremod, but it's not a GPU issue for sure.

Hard to debug and most likely not Charset's fault.

**Comment by 3TUSK** [comment]
*shrug*

*Pretend that this has never happened*
