### ISSUE TITLE
Compression crafting not working

### ISSUE THREAD

**Issue by stohun01** [asiekierka/CharsetMC#230]
Tested with a new profile that only had the mods listed below installed. The multi block does the squeezing animation and it has a valid recipe and output inventory but nothing is crafted or consumed.

Minecraft: 1.12.2
Forge: 14.23.3.2673
Charset Crafting: 0.5.0.244
Charset Lib: 0.5.0.244
Charset Storage - Barrels: 0.5.0.244

**Comment by asiekierka** [comment]
Does the issue persist on the latest version of everything? What particular recipe are you trying to accomplish?
