### ISSUE TITLE
[Suggestion] More compatibility with mod Redstone Paste in SimpleLogic

### ISSUE THREAD

**Issue by MaoDoBan** [asiekierka/CharsetMC#236]
Redstone wires on walls or on the ceiling of Mod Redstone Paste do not trigger the gates of SimpleLogic, functioning well only on the "floor".
I ask for this very helpful compatibility.

**Comment by asiekierka** [comment]
@FyberOptic Is there an API I can link to without coming in potential violation of the CC BY-NC-ND license?

**Comment by MaoDoBan** [comment]
I don't know

**Comment by asiekierka** [comment]
0.5.0.248a includes some steps towards proper support of Redstone Paste. It's not perfect, but it is a start.

**Comment by asiekierka** [comment]
And I guess it's sufficiently functional by now.
