### ISSUE TITLE
RS-Latch is not rotating correctly

### ISSUE THREAD

**Issue by mcenderdragon** [asiekierka/CharsetMC#238]
In 0.5.0.248b the RS-Latch is just rotating randomly. I starter at the same direct and placed the Latch a few times, each time the rotation was different. It is realy hard to build with it this way.

**Comment by asiekierka** [comment]
Why was the issue closed?

**Comment by mcenderdragon** [comment]
I figured it out. The rotation depended on the part of the block I locked at thats why it seemed so random. To avoid this maybe try to pre render the block when the player is holding the item, maybe then it is better undertsandable for new people (like me)

**Comment by asiekierka** [comment]
I'll probably make them utilize the arrow rotation, much like barrel placement already does.

**Comment by asiekierka** [comment]
Will be fixed in 0.5.0.248e.
