### ISSUE TITLE
Charset Block Carry lets you pick up bedrock

### ISSUE THREAD

**Issue by TheDeviantCrafter** [asiekierka/CharsetMC#240]
I don't mind moving spawners, but being able to move bedrock always seemed like it shouldn't be a feature.

**Comment by asiekierka** [comment]
That is correct! It shouldn't be a feature.

**Comment by asiekierka** [comment]
And it's actually a regression from long ago! I'm pretty sure I tested it against bedrock *originally*...

Fixed in 248f.
