### ISSUE TITLE
[Suggestion-Charset Storage - Chests] Compat quark buttons

### ISSUE THREAD

**Issue by Rikshy** [asiekierka/CharsetMC#251]
Hi there Asie!

Good talk yesterday :)

would it be possible for you do add support for the quark chest buttons? Or would that be on quarks end?

Incase you don't know which i mean:
![image](https://user-images.githubusercontent.com/6615662/43010015-8fffe02a-8c3f-11e8-8edc-6409339c422a.png)

greetings

**Comment by asiekierka** [comment]
It is on my side, yes.

However, I am not willing to link to the Quark API until this is resolved: https://github.com/Vazkii/Quark/issues/736

**Comment by Rikshy** [comment]
Seems like that vazkii doesn't care much about that subject :(

i know almost nothing about legal stuff so idc whats going on there

**Comment by asiekierka** [comment]
Well then, we'll have to wait.

**Comment by asiekierka** [comment]
I have released a new mod which should solve this issue called "Ion Chests".

**Comment by Rikshy** [comment]
the chest buttons don't seem to work. the search bar is tho (tested with charset chest 5.2.3
