### ISSUE TITLE
Charset somehow manages to break resource loader

### ISSUE THREAD

**Issue by Sunconure11** [asiekierka/CharsetMC#252]
I believe it's connected to this crash another user found. https://github.com/CharsetMC/Charset/issues/250

Somehow, resource loader is being messed up by the latest build of charset lib (0.5.2.1), but downgrading solves the issue.

By what I mean it's being messed up is that any resources set by it are turned back to their default textures, as opposed to the custom ones I've given.

**Comment by asiekierka** [comment]
"set by it"

Could you give a more concrete example, please?

**Comment by Sunconure11** [comment]
Er, say if I change the texture of cod to look like sushi rolls. They would end up reverting back to default vanilla textures.

**Comment by asiekierka** [comment]
So entity textures only? That's pretty weird - I thought I made very sure to only delete Charset's own textures.

**Comment by Sunconure11** [comment]
Items and blocks seem to be affected. I am not sure if entities are, but you might want to check anyways.

**Comment by Fortist** [comment]
Assie, the cods arent entities yet. 
But I think Im having a similar problem, my texture packs are being removed/disabled so I have to manually restore them in-game.  But this may not be an issue from this. Gonna test the new mods I added.

"Set by it" 
you see assie, when a texture pack (and resource loader) changes the texture of an item, the highest priority pack (resource loader > packs > mods > default) is the one used. So, resource loader SETS the texture.

**Comment by asiekierka** [comment]
https://asie.pl/files/Charset-0.5.2.2-pre-full.jar

Please test with this one!

**Comment by Fortist** [comment]
My problem seems to be unlimited chisel works, so, close enough.

I also have no idea how to use that .jar, since it just crashed me.

**Comment by asiekierka** [comment]
See https://github.com/CharsetMC/Charset/issues/254#issuecomment-406721625
