### ISSUE TITLE
[Bug] Viewing Recipe for Charset Chest made from Chisel Planks crashes

### ISSUE THREAD

**Issue by TeetoKaziim** [asiekierka/CharsetMC#254]
Versions of things (Entire modlist):
Forge: 14.23.4.2739
Charset Lib: 0.5.2.1 < -- EDIT: I forgot this.
Charset Storage - Chests: 0.5.2.0
Chisel: 0.2.0.31
Connected Textures Mod: 0.3.2.18
Just Enough items: 4.11.0.204

Crash Report generated:
https://gist.github.com/TeetoKaziim/42c4c3553bbea2ac6d221ae279e57ec8

Steps to reproduce:
Pretty simple. Open up JEI, search up planks, hit "U" on the plank, and then scroll through the recipes til you hit the charset chest recipe.
Alternately, open up JEI, search up your chest, and scroll through the recipes til you hit one using chisel planks.

Side note: It generated textures for the quark stained planks just fine in my "real" pack. :3 

Thanks for your time, the best to you.

**Comment by asiekierka** [comment]
Ah, now I remember! That's why I didn't want to just support arbitrary planks.

**Comment by asiekierka** [comment]
https://asie.pl/files/Charset-0.5.2.2-pre-full.jar

Please test with this one!

**Comment by TeetoKaziim** [comment]
Trying it out now. I'm kinda floundering because I'm more accustomed to working with the individual modules you have released on curseforge.

I'm supposed to only need the jar you've posted here? I'm not finding the chest in JEI, or creative tabs. And tab-complete on a /give doesn't seem to find them either? 

I seem to have the rest of the mod, though. Barrels, Rails, Keys and locks, Tanks, and Gates all are present.

![image](https://user-images.githubusercontent.com/25490944/43024072-a47ebf4c-8c32-11e8-809b-ef39a16e98b6.png)

I'm moderately certain I'm doing something wrong.

**Comment by asiekierka** [comment]
Oh. Oh, oh, ohhhh.

Sorry.

So. First of all, I don't generally publish test builds as the split JARs.

Second, I forgot about the module system. config/charset/charset.cfg -> set your profile to EXPERIMENTAL.

**Comment by TeetoKaziim** [comment]
EDIT: Ah, no worries, lemme do that instead

**Comment by TeetoKaziim** [comment]
Okay, set profile to experimental, loaded up, chests are present (along side a bunch of other fancy looking stuff I've never seen :3).

In this build, it appears the chisel planks no longer craft into chests? Is that the intended fix? (Considering what the chisel planks are, mind you, I think that's an acceptable fix. Their overall coloring doesn't vary much from the vanilla versions of those planks.) 

Other wood types still do. (In my test pack, that's just vanilla woods *and now quark stained planks)

![image](https://user-images.githubusercontent.com/25490944/43024622-863fcfd8-8c34-11e8-9f97-9df847ba6f7a.png)

EDIT: Added quark to test-environment, the stained plank chests still craft and display in JEI just fine.

**Comment by asiekierka** [comment]
Yes. I didn't want Chisel planks to work in the first place. I forgot they are oredicted. Thanks!
