### ISSUE TITLE
Overfilling a chest or your Inventory from a chest causes a freeze

### ISSUE THREAD

**Issue by Fortist** [asiekierka/CharsetMC#256]
No crashlog to give.
Shift clicking a bunch of items into a chest freezes the game when it gets to the final slot, or when shift clicking a bunch of items from a chest into your inventory.

**Comment by asiekierka** [comment]
Hmm. That's probably a global Charset bug, then.

**Comment by asiekierka** [comment]
Nice catch! Fixed in 0.5.2.3.
