### ISSUE TITLE
NPE if ore stone variants is also installed

### ISSUE THREAD

**Issue by xkforce** [asiekierka/CharsetMC#257]
https://paste.ee/p/IziCN

If either charset storage or ore stone variants is disabled, the game runs fine but if they're both installed, the game crashes with a NPE.  I am not sure where the issue actually is so I've also informed the OSV dev of the issue.

**Comment by xkforce** [comment]
just noticed this is a duplicate so I closed the issue.

**Comment by asiekierka** [comment]
Why did you update Storage.Chests and not Lib?

**Comment by xkforce** [comment]
Because I didn't realize that I accidentally removed the new file instead of the old one.  It works now that the new lib is installed.
