### ISSUE TITLE
NPE: java.util.concurrent.ExecutionException: org.joor.ReflectException

### ISSUE THREAD

**Issue by WenXin20** [asiekierka/CharsetMC#260]
Forge v14.23.4.2739-1.12.2
Charset Lib v0.5.2.3

My game freezes while loading but does not crash. I haven't had time yet to test to see if its another mod causing an issue with it. Here's the [full log.](https://gist.github.com/WenXin20/f87d8a53f174235bca825c9e501cdf72) Let me know if anymore info is needed.

**Comment by asiekierka** [comment]
That's a lot of coremods.

Try to rule the easy-to-remove ones out first - take out OptiFine, MakeZoomZoom and VanillaFix and tell me if any of them being removed changes anything. (You can keep FoamFix.)

**Comment by WenXin20** [comment]
It looks like the cause was MakeZoomZoom v0.0.4.0. If I need to, I can report it to them as well.

**Comment by asiekierka** [comment]
Absolutely, it's most likely an issue on that mod's side.
