### ISSUE TITLE
Error: java.lang.NoSuchMethodError: (SimpleLogicGates Model Error (or so I think))

### ISSUE THREAD

**Issue by marcguillemdev** [asiekierka/CharsetMC#261]
The game crashed whilst initializing game

`
**Error: java.lang.NoSuchMethodError: net.minecraftforge.common.model.TRSRTransformation.from(Lnet/minecraft/client/renderer/block/model/ModelRotation;)Lnet/minecraftforge/common/model/TRSRTransformation;**`

Game Version: 1.12.2

### _List of mods installed:_

> Charset-Lib-0.5.2.3.jar
> ChickenASM-1.12-1.0.2.7.jar
> CodeChickenLib-1.12.2-3.2.0.345-universal
> CTM-MC1.12-0.2.3.12.jar
> ForgeMultipart-1.12.2-2.4.2.60-universal.jar
> OptiFine_1.12.2_HD_U_E1.jar
> redstonepaste-mc1.12-1.7.5.jar
> SimpleLogic-Gates-0.5.2.0.jar
>

**Comment by asiekierka** [comment]
But what version of Forge are you using?

**Comment by marcguillemdev** [comment]
oops sorry, here is it:

> `Forge 1.12.2-14.23.2.2624`

**Comment by marcguillemdev** [comment]
### I ve updated Forge to 1.12.2 - 14.23.4.2705 but now SimpleLogicGates show an empty page in game.

http://oi68.tinypic.com/2znmk9l.jpg

**Comment by asiekierka** [comment]
Hmm. What happens if you install MCMultiPart?

**Comment by marcguillemdev** [comment]
The same, again the empty page

**Comment by asiekierka** [comment]
Hmm. That's weird. Did 0.5.3.0 fix it, perchance?

**Comment by marcguillemdev** [comment]
### Problem solved, thank you very much!  ;) ###

[The page is not empty :D](https://gyazo.com/e8b5f26181cb338c1b153b33660b9e26
)
