### ISSUE TITLE
[Ion Chests] Chest buttons do not work

### ISSUE THREAD

**Issue by Rikshy** [asiekierka/CharsetMC#264]
the chest buttons don't seem to work. the search bar is tho (tested with charset chest 5.3.0

**Comment by ChloeDawn** [comment]
Chest buttons..? The ones added by Quark?

**Comment by Rikshy** [comment]
Yes those! Asie made a compat mod between quark and IronChest and Charset Storage - Chests. => Ion Chests

**Comment by asiekierka** [comment]
Could you check if http://asie.pl/files/0533pre1_chests.zip affects anything?

**Comment by Rikshy** [comment]
sadly it doesnt :(

**Comment by asiekierka** [comment]
This has been narrowed down to a bug/issue in Quark.

**Comment by asiekierka** [comment]
https://github.com/Vazkii/Quark/pull/920
