### ISSUE TITLE
SimpleLogic Wires crash

### ISSUE THREAD

**Issue by ZapikCZ** [asiekierka/CharsetMC#266]
https://pastebin.com/uBeuz3Um

SimpleLogic Wires 0.5.3.1
forge 14.23.4.2739, though it happened with prior versions also

The game crashes, when I attempt to send a redstone signal through the wire. Placing them is fine, but when I, for example click a button or switch a lever connected to them, the game crashes.

**Comment by asiekierka** [comment]
Ah, yes. A fix is in the pipeline, but I thought I'd get more fixes in beforehand. Apparently not, so releasing 0.5.3.2!
