### ISSUE TITLE
Charset Chests don't behave right with Item Scroller

### ISSUE THREAD

**Issue by gchpaco** [asiekierka/CharsetMC#267]
When trying to scroll items out of a Charset chest using the https://minecraft.curseforge.com/projects/item-scroller mod (which works with every other kind of inventory I've used regularly) there's some super weird client desync that causes the target stack to disappear on the client in the Charset chest and for only one to transfer.  No items are actually lost, but it's very inconvenient.

**Comment by gchpaco** [comment]
I should note that I'm using Charset-StorageChests 0.5.3.0 and Item Scroller 0.12.0.

**Comment by asiekierka** [comment]
Fixed for future release.
