### ISSUE TITLE
Breaking Freestanding Redstone Cable drops Black Insulated Cable

### ISSUE THREAD

**Issue by angelnc1989** [asiekierka/CharsetMC#271]
Minecraft 1.12.2
Forge 15.23.4.2739
Charset Lib 0.5.4.0
SimpleLogic Gates 0.5.4.0
SimpleLogic Wires 0.5.4.0

When breaking a Freestanding Redstone Cable with a Redstone Cable connected to it, drops 1 Redstone Cable and 1 Black Insulated Cable.

**Comment by 3TUSK** [comment]
Can confirm w/ CharsetLib 0.5.3.1, SimpleLogic-Wires-0.5.3.2, demonstrated as below.

![2018-08-03_20 57 27](https://user-images.githubusercontent.com/9113033/43644057-f13f1678-975f-11e8-953b-423e0d99858a.png)
![2018-08-03_20 57 30](https://user-images.githubusercontent.com/9113033/43644059-f1aa9330-975f-11e8-87e3-df2cc67b093b.png)

**Comment by asiekierka** [comment]
Noticed. Working on a fix. The issue seems to be https://github.com/amadornes/MCMultiPart/issues/131 - but I can work around it on my side.

**Comment by asiekierka** [comment]
Fix finished, will be released in 0.5.4.1.
