### ISSUE TITLE
[Wires] Crash when wires interacting with redstone dust

### ISSUE THREAD

**Issue by ghost** [asiekierka/CharsetMC#272]
Hi!

I found a crash while making some redstone stuff and sadly I can't remember the exact setup, but I know it happened the exact moment I placed a solid block were there earlier had been a wire. (The standard type, not isolated.) And redstone dust was next to it.

I was trying to reproduce the error and I could crash the gamewhen placing redstone dust[d] and the wire[w] on the same y level, and then broke the block below one the redstone dusts, like this:

[d][d]
[w][w]

[Crashlog](https://paste.ee/p/wjDhO)

**Comment by asiekierka** [comment]
Fix slated for 0.5.4.4.

**Comment by ghost** [comment]
Thank you, that was quick :)
