### ISSUE TITLE
[Block Carrying] Lily Pads Cannot Be Placed

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#277]
If picking up a lily pad using block carrying, it cannot be placed again, and the player is forever stuck with the lily pad until they die, or invalidate the data through other circumstances.

**Block Carrying version:** [0.5.3.0](https://minecraft.curseforge.com/projects/charset-block-carrying/files/2590941)
**Charset Lib version:** [0.5.4.4](https://minecraft.curseforge.com/projects/charset-lib/files/2598195)
**Forge version:** [1.12.2-14.23.4.2747](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2747/forge-1.12.2-14.23.4.2747-changelog.txt)

**Comment by asiekierka** [comment]
Fixed by blacklisting lilypads in a future release, but I'm not 100% happy with that as a solution.

**Comment by asiekierka** [comment]
0.5.4.6
