### ISSUE TITLE
Wonky Charset tanks

### ISSUE THREAD

**Issue by 3TUSK** [asiekierka/CharsetMC#278]
Environment:

  * CharsetLib 0.5.4.4
  * Charset Storage Tanks 0.5.3.0
  * Forge 14.23.4.2747, singleplayer

Using vanilla water bucket and lava bucket to fill Charset tanks, or using vanilla empty bucket to drain Charset tanks with vanilla water or vanilla lava inside, are a bit wonky. Specifically:

  * When draining lava, sometime you can dupe buckets. Suppose I have a stack of empty buckets with size of 8, and 1 Charset tank filled with lava, right clicking with that stack of empty buckets may actually drain all lava out, or left 1000 mB bucket in tank. This is tested in survival mode. Similar glitch can also be observed when using Molten Manyullyn from Tinkers Construct instead (do notice that this time the filled bucket is the forge one, not vanilla one).
  * When filling water with vanilla water bucket, or draining water with vanilla empty bucket, if you have some vanilla empty glass bottle... those glass bottle are also sometimes consumed each time you right clicking Charset tank with vanilla water bucket. This is tested in creative mode. This does not happen in survival mode.

**Comment by 3TUSK** [comment]
Side note: may relate to #227; however the lack of details makes it hard to determine if both issue tickets are describing the same thing.

**Comment by asiekierka** [comment]
Fixed in 0.5.4.6. Note that the glass bottles will still seem to jump "in and out" in the inventory; this can be fixed, but requires additional work.
