### ISSUE TITLE
[Chests] Missing wood options

### ISSUE THREAD

**Issue by ghost** [asiekierka/CharsetMC#284]
Judging from the greatwood chest, I'm guessing you're looking for a log rather than planks. So it's probably not a surprise that there's no chest for EU2's magic wood, or AS's starlight infused wood.

Still, I wanted to put that out there so you could decide if you want to code for a few edge cases, look for planks, or let them pass.

Thanks

**Comment by asiekierka** [comment]
I'm looking for both a log and planks. They have to match.

For now:

    mods.charset.MaterialRegistry.registerTypes(<your_wood_plank>, "block", "wood", "plank");

**Comment by ghost** [comment]
I'm going to see if I can use stuff like CraftTweaker to create dummy "logs" to get chests for non-conforming wood.

**Comment by asiekierka** [comment]
You don't need to. Look at what I suggested above.

The requirement for Charset to notice a plank is for it to have a log, but that doesn't mean you can't force a plank yourself with the above command.

**Comment by ghost** [comment]
Or I could stop face-palming. :D
