### ISSUE TITLE
Crash and world corruption on placing charset barrel

### ISSUE THREAD

**Issue by ammy55** [asiekierka/CharsetMC#288]
I placed a barrel sideways on a garden cloche (with shift+right click) and crashed. I was then unable to open the world after restarting.
[crash-2018-08-10_21.00.01-server.txt](https://github.com/CharsetMC/Charset/files/2279918/crash-2018-08-10_21.00.01-server.txt)

**Comment by asiekierka** [comment]
What are the versions of your Charset modules? (I should really list this in the crashlog)

0.5.0.248h and 0.5.0.248b for Charset and SimpleLogic look *very* out of date.

**Comment by ammy55** [comment]
Charset-Crafting-0.5.0.248h.jar
Charset-Immersion-0.5.0.248e.jar
Charset-Lib-0.5.0.248h.jar
Charset-StorageBarrels-0.5.1.0.jar
Charset-Tablet-0.5.0.208.jar
Charset-TransportCartsRails-0.5.1.0.jar
Charset-Tweaks-0.5.0.248g.jar

**Comment by asiekierka** [comment]
Yes, please update to the latest versions of all of these first. In particular, Charset Lib 0.5.1.0+ is required for Barrels 0.5.1.0+...

Don't use out-of-date versions of the mod.

**Comment by ammy55** [comment]
Updating charset was gonna require updating forge and that broke other things, i rolled barrels and carts back to match lib and everything is copacetic now. Thanks asie.
