### ISSUE TITLE
Breaking wires does not always cause a redstone update

### ISSUE THREAD

**Issue by SquidDev** [asiekierka/CharsetMC#289]
## Mod versions 
 - Minecraft Forge 1.12.2 14.23.4.2749
 - SimpleLogic Wires and CharsetLib 0.5.4.6
 - MCMultipart 2.5.1

## Reproduction steps
 1. Setup a redstone lamp, redstone cable, insulated cable and a lever as so: ![image](https://user-images.githubusercontent.com/4346137/43990172-c51882f0-9d4f-11e8-9614-d34980ead3bc.png)
 2. Break the redstone cable on the lamp, leaving the insulated cable intact. [Observe the lamp remains on](https://user-images.githubusercontent.com/4346137/43990179-ec9b6806-9d4f-11e8-8ea4-3a66d7a845b8.png)
 3. Turn the lever off, or break it. [Note the lamp remains on](https://user-images.githubusercontent.com/4346137/43990184-0afc394c-9d50-11e8-98df-be9397a57692.png), despite there being no redstone signal. Triggering a block update fixes it.

I'm afraid I haven't looked too deeply into the code, so don't want to make a diagnosis - this is no #244. Sorry!

**Comment by asiekierka** [comment]
Thanks for the bug report anyway! I pretty much know what's wrong, and this should be an easy fix. Scheduled for 0.5.4.7/0.5.5.
