### ISSUE TITLE
Charset disconnects other players from LAN

### ISSUE THREAD

**Issue by The-Fireplace** [asiekierka/CharsetMC#29]
This is probably a problem on servers too, but I haven't tested with one.

When the host player moves, the other players get disconnected with a generic message saying a critical error has occurred. So, I looked at the other player's console and there was this error:
http://paste.ubuntu.com/14141802/

**Comment by asiekierka** [comment]
Is this still the case on Charset 0.1.1/MC 1.8.9?

**Comment by The-Fireplace** [comment]
I will tell you as soon as I am able to test it. The person I was testing it with broke her computer, but I can tell you once I update In-Game Account Switcher to 1.8.9
