### ISSUE TITLE
[cables] inconsistent bug of inconsistent timing between gates and vanilla repeater

### ISSUE THREAD

**Issue by cola98765** [asiekierka/CharsetMC#297]
![2018-08-12_13 10 22](https://user-images.githubusercontent.com/10381827/44001388-608df1fc-9e31-11e8-9ccf-b6e45a8a31f2.png)
lamps light up in orden shown by roman numerals on screenshot
lamps III, and IV light up really close to each other (closer to what I think should be)

From top we can see
-line of 20 buffer gates connected to loops after 20th
-line of 20 vanilla repeaters connected to loops after 10th
-OR gate loops so we can see it's not just graphical bug
-line of 20 OR gates connected to loops after 20th

Both lines of gates should have same timing.
If charset gates use MC ticks (20/s) 20 gates should line with 10 repeaters (so lamps III, IV, and V line up)
If charset gates use RS ticks (10/s) 20 gates should line with 20 repeaters (so lamps IV, V, and VI line up)

**Comment by asiekierka** [comment]
Oh dear.

**Comment by asiekierka** [comment]
Fixed in 0.5.5.
