### ISSUE TITLE
[cables] some gates does not show correctly what state they are in

### ISSUE THREAD

**Issue by cola98765** [asiekierka/CharsetMC#298]
In order in creative tab
1)Synchroniser
![2018-08-12_14 08 06](https://user-images.githubusercontent.com/10381827/44001830-57f232bc-9e39-11e8-8793-813e853770ef.png)
Whatever state this gate is in right wire (marked II) is lit.
Output torch (marked I) is lit when gate does not output and is dark when is outputting.

2)Set-Reset Latch
![2018-08-12_14 15 22](https://user-images.githubusercontent.com/10381827/44001885-3eb0d8f2-9e3a-11e8-83df-1bbfd385b5a4.png)
This is minor. there should be flat wire where signal is taken from torch in marked spots similar to eg. OR gate

3)XOR Gate
![2018-08-12_14 19 22](https://user-images.githubusercontent.com/10381827/44001924-d6a7b6e4-9e3a-11e8-926d-1b6f231f6cc1.png)
Marked torch work in opposite than it should.

4)Multiplexer
![2018-08-12_14 21 44](https://user-images.githubusercontent.com/10381827/44001944-43aa80e6-9e3b-11e8-8ed9-ebd730eecbb4.png)
Output torch (marked I) does not correlate to output state, only to input (marked II).

5)Pulse Former
![2018-08-12_14 24 59](https://user-images.githubusercontent.com/10381827/44001956-92fa24b2-9e3b-11e8-9a19-8e40b0d6b5ab.png)
Marked torch work in opposite than it should.

6)XNOR Gate
![2018-08-12_14 26 11](https://user-images.githubusercontent.com/10381827/44001985-d64f06b0-9e3b-11e8-9d99-bcf1060153b9.png)
This is minor. Marked part of wire work in opposite than it should.

**Comment by asiekierka** [comment]
![](https://evolveslc.files.wordpress.com/2011/07/wpid-photo-jul-6-2011-1242-pm.jpg)

**Comment by asiekierka** [comment]
Fixed in 0.5.4.8. I hope. Please double-check.
