### ISSUE TITLE
NPE with Shifter Destination being another Shifter

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#3]
Got another one for you! [Here's the crashlog](http://paste.ee/p/PstlY), and here's a photo of the setup I had before it crashed (granted, no items are in the chest to avoid the crash from happening before I could photograph it:

![2015-12-01_10 48 51](https://cloud.githubusercontent.com/assets/3887324/11505600/4b62e0ec-9819-11e5-82f1-0d041f107b77.png)

The coal was pulled out of the left shifter, and seemed to be sending the item to the right shifter, but of course upon arrival, crashed.

**EDIT**

Also happens if the items get sent out but have no destination at all. Just discovered that. So it wasn't that they were routing towards the other shifter, they simply reached the end of the Pipe line and could not determine where to go, and instead of doing your freezing / locking / jamming animation, they're sending the user to the desktop :P

**Comment by asiekierka** [comment]
No, it's just another missing nullcheck.

**Comment by asiekierka** [comment]
Fixed, but there's a different bug which happens on world reload attempt. No idea why, maybe it's devenv-only.
