### ISSUE TITLE
Note Block Gate

### ISSUE THREAD

**Issue by SoniEx2** [asiekierka/CharsetMC#30]
Plays a note.

I/O: Back (analog) decrements note by signal strength, front (analog) increments note by signal strength, left (digital) modifies increment/decrement size, right (digital) triggers note.

Crafted with a note block. Right-click with a block to insert instrument.

Optionally compatible with [NoteBetter](https://github.com/eNByeX/NoteBetter) by using a fake world.

See https://github.com/Qmunity/BluePower/issues/265#issuecomment-105923062 and https://github.com/Qmunity/BluePower/pull/361

**Comment by asiekierka** [comment]
Too stateful. I have my own plans.

**Comment by SoniEx2** [comment]
But can we get a note block gate? Maybe make it check the block it's on, and remove the current note state?
