### ISSUE TITLE
Bundled cables don't update properly

### ISSUE THREAD

**Issue by Wieku** [asiekierka/CharsetMC#307]
Video describing the issue: https://youtu.be/YMmLMnYTZ-k
This bundled cable also updates if someone joins the server or after some random time.

**Comment by Wieku** [comment]
I forgot to mention that some colors inside this bundled cable works properly.

**Comment by cola98765** [comment]
![2018-08-13_10 15 52](https://user-images.githubusercontent.com/10381827/44020389-0abe7a24-9ee2-11e8-9a28-83d798cc4178.png)
this work when using RS latch and insulated cable length is >= 4

**Comment by asiekierka** [comment]
Fixed in 0.5.5.
