### ISSUE TITLE
Freestanding bundled cable connects with gate

### ISSUE THREAD

**Issue by Acerixx** [asiekierka/CharsetMC#308]
![2018-08-13_03 43 09](https://user-images.githubusercontent.com/9009175/44009301-2e7aca9e-9eab-11e8-8998-52adeee66a56.png)
![2018-08-13_03 43 11](https://user-images.githubusercontent.com/9009175/44009306-31baa4e0-9eab-11e8-9198-75b6992aa918.png)

**Comment by asiekierka** [comment]
Fixed in 0.5.4.8.
