### ISSUE TITLE
Launch Crash with Charset 0.1.0

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#31]
Just going to leave [this log](http://paste.ee/p/vBzHk) here. I only have Forge 11.15.0.1684, Baubles (accidentally left it installed, but shouldn't be causing this crash), Charset 0.1.0 (this jar is without **&**, but the same crash occurs with **&** too), and MCMP 1.0.2.

Looks like an outdated Lib? Not sure :P

**Comment by GirafiStudios** [comment]
Updated MCMP to 1.0.3 ? :p
