### ISSUE TITLE
Simple Logic Wires crash on startup

### ISSUE THREAD

**Issue by angelnc1989** [asiekierka/CharsetMC#311]
Minecraft 1.12.2
Forge 14.23.4,2749
Charset Lib 0.5.4.8
Simple Logic Gates 0.5.4.8
Simple Logic Wires 0.5.4.8

https://pastebin.com/Ujxbmxqt

**Comment by asiekierka** [comment]
AUGH

**Comment by asiekierka** [comment]
Fixed version incoming.

**Comment by angelnc1989** [comment]
Damn you're fast
