### ISSUE TITLE
When there's a bundled cable connected to a gate and there's a freestanding cable in the same block the signals mix

### ISSUE THREAD

**Issue by Matrix89** [asiekierka/CharsetMC#313]
https://img.bymarcin.com/2018-08-14_02-11-29_fMX0OueMKrRRtBnM.mp4
https://img.bymarcin.com/2018-08-14_02-17-43_YB0cNMromLhTvcYR.mp4

**Comment by asiekierka** [comment]
Acknowledged.

**Comment by asiekierka** [comment]
Fixed in 0.5.5.
