### ISSUE TITLE
Compatibility issue with Charset Chests

### ISSUE THREAD

**Issue by Rufflikerex** [asiekierka/CharsetMC#316]
Here's the info I got:
-Both Normal Chests and Charset Chests can have locks applied to them while sneaking.
-(Edit: While not sneaking) Normal chests can be opens with keys and the lock in hand. The Charset Chests cannot.

Log info:
> [05:54:18] [main/FATAL] [net.minecraft.client.Minecraft]: Unreported exception thrown!
> java.lang.NoClassDefFoundError: pl/asie/charset/lib/utils/MultipartUtils
> 	at pl.asie.charset.module.storage.chests.TileEntityChestCharset.isBlocked(TileEntityChestCharset.java:231) ~[TileEntityChestCharset.class:?]
> 	at pl.asie.charset.module.storage.chests.TileEntityChestCharset.activate(TileEntityChestCharset.java:282) ~[TileEntityChestCharset.class:?]
> 	at pl.asie.charset.module.storage.chests.BlockChestCharset.func_180639_a(BlockChestCharset.java:140) ~[BlockChestCharset.class:?]
> 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423) ~[bsa.class:?]
> 	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96) ~[PlayerControllerOF.class:?]
> 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1578) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Caused by: java.lang.ClassNotFoundException: pl.asie.charset.lib.utils.MultipartUtils
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
> 	... 18 more
> Caused by: java.lang.NullPointerException
> [05:54:20] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   CharsetPatchCore (CharsetPatches-0.1.6.jar)
>   AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
>   CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
>   SCFMLCorePlugin (StalkerCreepers-1.12.1.jar)
>   TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.11-core.jar)
>   TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
>   SmoothWaterCore (SmoothWater-0.1.4.jar)
>   Narrator Hotkey Disabler (rebindnarrator-1.0.jar)
>   SSLoadingPlugin (SereneSeasons-1.12.2-1.2.3-universal.jar)
>   llibrary (llibrary-core-1.0.8-1.12.2.jar)
>   ComfortsCoreLoadingPlugin (comforts-1.12.2-1.2.0.jar)
>   IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
> Contact their authors BEFORE contacting forge
> 
> // Shall we play a game?
> 
> Time: 8/15/18 5:54 AM
> Description: Unexpected error
> 
> java.lang.NoClassDefFoundError: pl/asie/charset/lib/utils/MultipartUtils
> 	at pl.asie.charset.module.storage.chests.TileEntityChestCharset.isBlocked(TileEntityChestCharset.java:231)
> 	at pl.asie.charset.module.storage.chests.TileEntityChestCharset.activate(TileEntityChestCharset.java:282)
> 	at pl.asie.charset.module.storage.chests.BlockChestCharset.func_180639_a(BlockChestCharset.java:140)
> 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
> 	at net.optifine.override.PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
> 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1578)
> 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
> 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: pl.asie.charset.lib.utils.MultipartUtils
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 18 more
> Caused by: java.lang.NullPointerException

**Comment by asiekierka** [comment]
Lib/Chests version mismatch
