### ISSUE TITLE
Wires Don't Stay on the side of Extended Pistons

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#32]
Wires are whitelisted to stay on the sides of a normal piston / sticky piston, right? Seems as though they are NOT for the side of an extended piston's base, so when I retract the piston, the wire updates and flies off. Proof:

Before:
![2016-01-06_14 36 57](https://cloud.githubusercontent.com/assets/3887324/12154074/ff3d26d8-b482-11e5-8fb8-cfbd9ed8d789.png)

After:

![2016-01-06_14 37 00](https://cloud.githubusercontent.com/assets/3887324/12154077/0270e7fe-b483-11e5-8e07-486d270ba421.png)

Also Notch Fix boats

**Comment by nabijaczleweli** [comment]
I remember asie saying he fixed boats in some modpack a while back.
