### ISSUE TITLE
Signals are doubling in cables

### ISSUE THREAD

**Issue by Wieku** [asiekierka/CharsetMC#323]
https://youtu.be/rOW3WKF0wao

**Comment by Matrix89** [comment]
![](https://matrix89.me/matrix/2018-08-17_00-36-08.gif)

**Comment by asiekierka** [comment]
Fixed in 0.5.5.

**Comment by asiekierka** [comment]
Related to #307

**Comment by asiekierka** [comment]
Only fixed in simple cases. needs more work

**Comment by asiekierka** [comment]
Fixed for real.
