### ISSUE TITLE
Connection Issue with Chisels and Bits

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#33]
Was trying to play with bundled wire when I was foiled by a silly bug! D:

Here's the issue. I don't know if it's got to do with the face, or if maybe I don't understand something? Not sure... and it might be on Chisels and Bits side of things, but I don't think so.

Anyways, here's what happens:

![2016-01-10_16 53 16](https://cloud.githubusercontent.com/assets/3887324/12224287/d493776c-b7ba-11e5-8971-6d0559d0c29a.png)

And here's what was expected (and what works on the top face of a block, specifically):

![2016-01-10_16 53 19](https://cloud.githubusercontent.com/assets/3887324/12224289/df934570-b7ba-11e5-87a9-974bd6ef9b09.png)

**Comment by asiekierka** [comment]
Could you try compiling the latest build? I did some relevant fixes in 0.1.3.

**Comment by oitsjustjose** [comment]
I'm on it! :D

**Comment by oitsjustjose** [comment]
Yup, it's fixed - on top of it as always!
