### ISSUE TITLE
[0.5.5.1] StackOverflowError: Exception while updating neighbours

### ISSUE THREAD

**Issue by marcin212** [asiekierka/CharsetMC#333]
log: https://img.bymarcin.com/crash-2018-08-18_01.06.55-server.txt

**Comment by asiekierka** [comment]
![](https://vignette.wikia.nocookie.net/nichijou/images/0/0f/Ep2_yuuko_mio_reaction_face.png/revision/latest?cb=20110812022106)

**Comment by asiekierka** [comment]
Fixed in 0.5.5.2.
