### ISSUE TITLE
Simple Gates / Charset Crash on 1.12.2

### ISSUE THREAD

**Issue by MrCurry1989** [asiekierka/CharsetMC#335]
Installed a recent version of Charset, Simple Gates / Wires and other mods to play today, but i encountered this error i never saw before on old builds.

Pastebin: https://pastebin.com/49zG3axF

**Comment by asiekierka** [comment]
Did you update SimpleLogic Gates to 0.5.5.x?

**Comment by MrCurry1989** [comment]
Yes, i did

**Comment by asiekierka** [comment]
Are you sure? That's not what the log says.

**Comment by MrCurry1989** [comment]
I did, it is 0.5.5.1, the same as on the curseforge page. I was playing now without Simple Gates, it didn't crash now.

**Comment by asiekierka** [comment]
The code calling rotateVec() was removed in SimpleLogic Gates 0.5.5.0. It's literally impossible for this to happen if you have the correct JAR...

**Comment by MrCurry1989** [comment]
Nvm, i'm just too stupid to read versions of things, sorry for the trouble, i'm really sorry for bothering you.

**Comment by asiekierka** [comment]
Don't worry about it! We all make mistakes sometimes.
