### ISSUE TITLE
[Request] Charset Tablet JEI Integration

### ISSUE THREAD

**Issue by ScottoMotto** [asiekierka/CharsetMC#336]
Would it be possible to add a keybinding to look up items in a held Tablet when they are hovered over in JEI? 

I am just discovering the usefulness of the tablet in-world, for instance with Tech Reborn. However, that requires that one has already made the machine. 

Using the Tablet as Tech Reborn documentation is a good example because in the current layout of the wiki there seems to be no other way to get to the "Items" and "Blocks" sections without using the in-world item to trigger the link. This of course not an issue with the Tablet functionality. JEI integration would overcome issues like this.

**Comment by asiekierka** [comment]
Why limit myself to JEI? :thinking:

**Comment by asiekierka** [comment]
Added in 0.5.5.2.

**Comment by asiekierka** [comment]
Great, apparently the current implementation doesn't quite catch JEI yet. I'll improve it for 0.5.5.3.

**Comment by asiekierka** [comment]
Added in 0.5.5.3.

**Comment by ScottoMotto** [comment]
Yeah, super nice. It works great. Nice choice for default keybind as well. Thank you.
