### ISSUE TITLE
Wire color rendering bug w/ shaders installed

### ISSUE THREAD

**Issue by TimGoll** [asiekierka/CharsetMC#349]
![wire_1](https://user-images.githubusercontent.com/13639408/44988997-bca4cf80-af8c-11e8-83f5-2d19aae43a4d.jpg)
![wire_2](https://user-images.githubusercontent.com/13639408/44988998-bca4cf80-af8c-11e8-9cbd-e415cf7e5e04.jpg)

Newest version of your mod for 1.12.2

There are come color glitches. Ingame and in JEI. Maybe it is caused by optifine. I can test it without it if it'd help you.

**Comment by asiekierka** [comment]
Looks like shader issues to me. Try without shaders first.

**Comment by TimGoll** [comment]
![wire_3](https://user-images.githubusercontent.com/13639408/44989474-3db09680-af8e-11e8-97e5-bc5b22030c87.jpg)

You were absolutely right! It works without a shader. In case you want to fix the shader issue, I'm using this one: http://bitslablab.wixsite.com/main/bsl-shaders

**Comment by asiekierka** [comment]
Unfortunately, both of my integrated GPUs are too slow to handle any reasonable shader pack. Can't help you there, sorry.

**Comment by TimGoll** [comment]
I looked a bit though your code and tested a few things.
The default redstone wire and the bundled wire (uncoloured) are rendered properly. Only the colored ones have problems. Maybe this helps.
I thought this line was interesting `int c = 0xFF000000 | EnumDyeColor.byMetadata(v).getColorValue();` but it should be all black if there is an error with that.

**Comment by asiekierka** [comment]
Found something that looked off, and fixed it in 0.5.5.5. Might help, might not. Let me know!

**Comment by asiekierka** [comment]
I'd check myself, but OptiFine crashes Mesa drivers on *both* of my Intel/Linux-powered laptops. And that's without shaders! :/

**Comment by TimGoll** [comment]
I'll test it! Have you already published it on Curse?
Feel free to send me jars for testing purposes

**Comment by asiekierka** [comment]
It's on my website. It will appear on Curse whenever they get around to it.

**Comment by TimGoll** [comment]
Okay. I'm currently at work. I'll test it in a few hours. Thanks for your work

**Comment by TimGoll** [comment]
I checked your website (https://charset.asie.pl/download/) but there is no version 0.5.5.5) and wasn't able to find a download from today

**Comment by asiekierka** [comment]
It was there all along, forgot to propagate the links. Fixed now.

**Comment by TimGoll** [comment]
Yep, it does work! The colors are now rendering perfect. Thank you :)

**Comment by asiekierka** [comment]
Excellent :)
