### ISSUE TITLE
Crash when attempting to break pipe/wire

### ISSUE THREAD

**Issue by Ayrrow** [asiekierka/CharsetMC#35]
Placed a pipe connecting a chest, placed a redstone wire (normal/unsupported/undyed) beneath the pipe. 

Attempting to break the pipe causes this crash. Latest versions of both Charset and MCMP. Reproduced in creative.

http://paste.ee/p/JUKdG

**Comment by asiekierka** [comment]
Bug in MCMultiPart, will be fixed in 1.0.5 (or compile from GitHub!)

2016-01-18 2:55 GMT+01:00 Ayrrow <notifications@github.com>:
