### ISSUE TITLE
Gamecrash on opening Timer GUI

### ISSUE THREAD

**Issue by TimGoll** [asiekierka/CharsetMC#351]
Minecraft 1.12.2, newest charset stuff. Game crashes after rightcklicking on the timer

Crashlog: https://gist.github.com/TimGoll/4d516ccc4df3dd412918f9e4e2cb2130

**Comment by asiekierka** [comment]
>shaders

Try without shaders.

**Comment by TimGoll** [comment]
ahh, your mod hates shaders :D
I'll try it!

**Comment by asiekierka** [comment]
Yes, not even the first shader-related issue.

I use Forge's model systems in uncommon ways.

**Comment by TimGoll** [comment]
The last shader issue was by me too^^

I'll try it later without shader and let you know if it works indeed. I'm pretty sure it does

**Comment by TimGoll** [comment]
Short update:
The problem is not related to the GUI. The GUI does work. At some random points on breaking, placing or klicking this timer the game crashes. The error is everytime from the same entity. Maybe this helps if you consider fixing it

**Comment by TimGoll** [comment]
Sidenote: After restarting the game and reloading the map the game crashes again. I have to remove the timer block to be able to load the map. Error is still the same

**Comment by asiekierka** [comment]
Fixed in 0.5.5.5.

**Comment by TimGoll** [comment]
Either I'm stupi or you added a new bug. I'm unable to open the timer GUI alltogether^^

**Comment by TimGoll** [comment]
Nevermind, it seems to work now. I don't know why I wasn't able to do this before

**Comment by calloatti** [comment]
https://paste.dimdev.org/mocicayigi.mccrash

https://paste.ee/p/jRpOr

Where is the download for 0.5.5.5

**Comment by asiekierka** [comment]
That's a *different* crash. Please open a new issue.
