### ISSUE TITLE
[charset chests] chest recipes do not show up in JEI

### ISSUE THREAD

**Issue by xkforce** [asiekierka/CharsetMC#356]
Chests can be crafted just fine from pretty much any plank registered to the plankWood ore dictionary but the recipe for them doesn't show up in JEI or the recipe book.

**Comment by asiekierka** [comment]
Could not reproduce.

**Comment by xkforce** [comment]
nm it's the recipebook not jei. closed

**Comment by asiekierka** [comment]
Charset, indeed, does not make great efforts to support the recipe book.
