### ISSUE TITLE
Invisible w/ Optifine

### ISSUE THREAD

**Issue by WenXin20** [asiekierka/CharsetMC#36]
Pipes, wires, & redstone components were invisible when optifine was added with the mod.

**Comment by asiekierka** [comment]
OptiFine tends to break things. If Chisels & Bits stuff is also invisible,
it's an MCMultiPart/OptiFine bug, if not...

2016-01-18 3:00 GMT+01:00 WenXin20 <notifications@github.com>:

**Comment by WenXin20** [comment]
I used both chisel and bits and your mod, and the bits from chisels and bits were visible, but not the pipes from the charset mod

**Comment by asiekierka** [comment]
In the same block space?

**Comment by WenXin20** [comment]
Yes, and only the chisel bits were visible

**Comment by WenXin20** [comment]
And the stuff from the charset mod were invisible when by itself as well.

**Comment by asiekierka** [comment]
Does disabling Fast Render help?

**Comment by WenXin20** [comment]
No

**Comment by asiekierka** [comment]
Will not be looked at for 1.8.9 as it is being abandoned. If the issue re-occurs on 1.9, please let me know.
