### ISSUE TITLE
Chests - Quark chest buttons and search bar missing

### ISSUE THREAD

**Issue by AtomicWaffle14** [asiekierka/CharsetMC#362]
The chest GUI buttons (like sorting) and search bar from Quark are not visible in Charset chests. Can this be fixed for consistency's sake?

**Comment by asiekierka** [comment]
For licensing reasons, these are in a separate mod http://minecraft.curseforge.com/projects/ion-chests

**Comment by Winddbourne** [comment]
Could we get this listed as a thing on the page? I was wasting time trying to get a GUI ID using quarks chest button options to enable them. . . it was very frustrating. Going to go look for Ion Chests now.
