### ISSUE TITLE
Don't Work With Translocators Mod [ISSUE]

### ISSUE THREAD

**Issue by Feranogame** [asiekierka/CharsetMC#364]
This is the PERFECT barrel mod for my modpack, but it doesn't work with item translocators mod, that is essential in the pack, please fix it.

**Comment by asiekierka** [comment]
Are you extracting from the bottom and inserting from the top or back of the barrel?

**Comment by Feranogame** [comment]
Item translocators should extract from any side and input from any side, it is what differs it from hoppers.

**Comment by asiekierka** [comment]
No. Barrels can only be extracted from from the bottom and inserted from the top or back. Try it with any pipes from any mod.

This is how barrels work. They don't have holes on the sides! This is also a good time to use the rotation feature of barrels - you can orient them in 24 different orientations to match your build's needs.
