### ISSUE TITLE
Major log spam with player damage animation

### ISSUE THREAD

**Issue by brisingraerowing** [asiekierka/CharsetMC#365]
[Error Log](https://paste.dimdev.org/hocilozibi.mccrash) (courtesy of VanillaFix)

I was in creative at the time, FWIW, having switched from a bizarre broken gamemode. (My pack has a bug that causes the player to start in a weird gamemode that isn't one of the three normal ones. I have hearts and hunger bars, can fly, and can't place blocks (but I can break them instantly). Mobs also don't attack me and I can't take damage)

**Comment by asiekierka** [comment]
Fixed in 0.5.5.7.
