### ISSUE TITLE
Everything except JEI freezes on second load of File Dialog

### ISSUE THREAD

**Issue by ghost** [asiekierka/CharsetMC#367]

**Comment by bgbrandongomez** [comment]
@asiekierka How do you get the audio part of the mod working? I compiled branch [1.12-stable](https://git.asie.pl/asie-minecraft/Charset/src/branch/1.12-stable) and I got items from your mod and the other mods this hooks into such as JEI to load (when I run ./gradlew runClient), but I cannot find any of the items such as the record player to show up in the creative tab or JEI.

Is the branch missing those items (as in it wasn't created yet) or am I missing a dependency to get it to show up)? I already tried with the "Charset-Audio-0.5.5.6" dependency, but it crashed the client when forge was preloading the mods.

I am working on fixing the mod myself so I can play my game without the bug interfering with my game.

**Comment by asiekierka** [comment]
Set the profile to EXPERIMENTAL in charset.cfg. Artifacts of a bygone era...
