### ISSUE TITLE
[Charset Storage - Chests]  Breaking animation colors are incorrect on some chests

### ISSUE THREAD

**Issue by TheDeviantCrafter** [asiekierka/CharsetMC#368]
On the darker chest types such as dark oak, the color of the breaking animation doesn't seem too out of place. On lighter colors such as oak and jungle, the color seems to have too much red or yellow and it stands out.

I tested a handful of the 50+ chests in the pack I'm currently playing. Pale colors on the red-orange-yellow side of the color wheel seem to be affected the strongest. Green chests have too much yellow and red-orange chests are far too red.

The color of the chest itself seems to perfectly match the plank it's made from. It's the breaking animation that seems wrong.

Here's an example:

![2018-12-18_19 52 48](https://user-images.githubusercontent.com/18755309/50194175-4e97d480-02ff-11e9-869f-c307399bfca6.png)

Forge version: 14.23.5.2796

Charset Storage - Chests version: 0.5.5.6

Charset Lib version: 0.5.5.6

**Comment by asiekierka** [comment]
It's based on how Minecraft overlays textures on top of each other. I'm not sure if I can do a whole lot to fix this.

**Comment by asiekierka** [comment]
Fixed in 0.5.5.7, actually was my fault.
