### ISSUE TITLE
[0.5.5.6] Channel name already used: chrs:gates

### ISSUE THREAD

**Issue by TheSpiderDungeon** [asiekierka/CharsetMC#379]
https://pastebin.com/EsUML0B8

Minecraft just... Refuses to start unless I remove Charset.

**Comment by asiekierka** [comment]
You sure you don't have two SimpleLogics?

**Comment by TheSpiderDungeon** [comment]
Turns out I did. I feel REALLY dumb. Thanks for taking the time to reply
anyway; I really appreciate it!
