### ISSUE TITLE
Equipping a non-backpack chestplate and then having a backpack in inventory causes it to get stuck.

### ISSUE THREAD

**Issue by Laskeri** [asiekierka/CharsetMC#38]
I'm using the latest version with all modules installed, and latest forge. 
http://paste.ee/p/iQ1dg Here's a log but I'm not sure if it's relevant. I died a few times near the end and that removed the chestplate, but I was able to recreate this issue multiple times.
Having a backpack in your inventory also prevents any chestplates from being equipped regardless of whether or not the backpack is equipped.
I also tested it with just Charset and MCMultipart and it was repeatable.

Sorry if this is a known issue.

**Comment by copygirl** [comment]
Additionally, when logging in the chestplate slot is not modified and it's possible to simply unequip it in the player inventory GUI.
