### ISSUE TITLE
Can't insert/extract into barrels with Ender IO's item conduit

### ISSUE THREAD

**Issue by mser7** [asiekierka/CharsetMC#381]
The conduit did connect to the barrel, but you can't insert of extract items from it, tested on normal and hopping barrel, vanilla hopper worked fine.

**Comment by asiekierka** [comment]
Extraction works just fine - make sure you're doing it from the barrel's (relative) bottom. As does insertion, from the relevant sides. Tested on latest Ender IO versions.
