### ISSUE TITLE
[Immersion] [Feature request] Place collected items directly in inventory

### ISSUE THREAD

**Issue by Froggy800** [asiekierka/CharsetMC#382]
Hi Asie; I would like to request the addition of a config to make it so that when you collect items from in-world stacks they go directly in the player's inventory, be it a single item or the entire stack.

**Comment by asiekierka** [comment]
There is already such a config option in Charset; I guess it's not applied to Immersion...

**Comment by asiekierka** [comment]
Fixed in 0.5.5.7.
