### ISSUE TITLE
Crash after inserting a BuildCraft Strip Pipe into Barrel

### ISSUE THREAD

**Issue by 3TUSK** [asiekierka/CharsetMC#385]
Game crashes after I accidentally placed a piece of Strip Pipe from BuildCraft into a normal Charset Oak Wood Barrel and look at the front of the barrel. The save is not corrupted; but you still cannot continue use that save because you would be still looking at the front of the barrel after you re-opened the save.

Crash report: https://paste.ee/p/Keaar
All related info may be found at the end of the crash report.

**Comment by asiekierka** [comment]
Paste not found :|

Please use more permanent pastebins, GitHub Gists, or anything of the sort next time.

**Comment by asiekierka** [comment]
"Fixed" in 0.5.5.7.

**Comment by 3TUSK** [comment]
Wait how could you fix things without corresponding crash report? Or did you replicate the issue on your own?

**Comment by asiekierka** [comment]
I replicated the issue on my own. It's a BuildCraft bug, but I added safeguards to prevent from crashing in case another mod is similarly broken.

**Comment by 3TUSK** [comment]
For sake of xkcd 979, here is the original crash report: https://paste.ubuntu.com/p/97gRfGYMBx/
