### ISSUE TITLE
Investigate recipes not being deleted properly

### ISSUE THREAD

**Issue by immortaleeb** [asiekierka/CharsetMC#39]
The tweak that disables vanilla tools is enabled by default and actually set to 2 which tries to disable vanilla tool recipes.

Also: setting this config to 2 doesn't seem to actually disable vanilla tools recipes but does remove recipes for mod tools that extend the vanilla tool classes.

Tested on Charsets 0.1.5

**Comment by asiekierka** [comment]
oh

**Comment by KaseiFR** [comment]
Yup, I just spent an hour isolating the mod responsible for this ^^

By default, Vanilla tools are uncraftable, and some modded tools (BM sentient sword for example) only have 2 durability.

**Comment by asiekierka** [comment]
I fixed the default part in 0.1.6. Let's do the rest for 0.2.0...

**Comment by asiekierka** [comment]
>Also: setting this config to 2 doesn't seem to actually disable vanilla tools recipes but does remove recipes for mod tools that extend the vanilla tool classes.

I just realized that's intentional, as the config was designed specifically for TCon users.
