### ISSUE TITLE
Simplelogic Wire and gates not in the load order or in the game

### ISSUE THREAD

**Issue by 4498Lincoln** [asiekierka/CharsetMC#392]
There isn't a crash report for me to provide but there is the list of mods for me to provide. both SimpleLogic mods Gates and Wires aren't appearing in my game. Yes, I did check the mod load order in the ingame mod menu.

Mods: 
![image](https://user-images.githubusercontent.com/49529648/55988084-ce073600-5c57-11e9-97c6-3cf89c274be3.png)

I am using the latest forge version, well, version 14.23.5.2827 for 1.12.2

**Comment by 4498Lincoln** [comment]
Using curseforge SimpleLogic mods, curseforge MCMultiPart and curseforge Charset. The image of my mods is outdated, as it shows a 9Minecraft MCMultiPart. BTW again I am using the latest MCMultiPart

**Comment by NotReallyACat** [comment]
Did you fix this?

**Comment by 4498Lincoln** [comment]
> 
> 
> Did you fix this?

Yes, I did.

**Comment by TheFlash787** [comment]
> 
> 
> > Did you fix this?
> 
> Yes, I did.

What was the fix? If you remember.

Thank you!
