### ISSUE TITLE
Simplelogic is not loading

### ISSUE THREAD

**Issue by NotReallyACat** [asiekierka/CharsetMC#393]
FML has found a non-mod file SimpleLogic-0.5.5.7.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible. 

^noticed that in log only reference to simplelogic

Are you sure the latest version is for 1.12.2

**Comment by asiekierka** [comment]
Yes. You must have CharsetLib (or Charset) installed as well, at which point despite this warning the mod should be loaded properly (as part of Charset).
