### ISSUE TITLE
[Not A Crash This Time] Pipe Priority Issues

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#4]
So I'm just going to leave this one here. It's not game crashing, so that's wonderful! BUT:

Pipes seem to have a destination in mind, and then if they arrive and cannot insert, jam instead of searching for alternatives. Is this intended? For example, I put both gold and Iron ore in the same chest to be extracted into an ElectroExtractor (of which I had 4 hooked up), and they both left the chest pretty quickly. The Gold Ore beat the Iron, and instead of the Iron going to one of the other 3 connected ElectroExtractors, it just sits above the originally mapped one and waits.

<3

![2015-12-01_12 07 04](https://cloud.githubusercontent.com/assets/3887324/11507909/3c5e9446-9824-11e5-8016-3afb2d5503fc.png)

**EDIT**

Also, the shifter / pipe setup beneath the ElectroExtractors isn't working ideally either. Some of the Electrolytic Gold Dust is trying to path to the other shifters (then falling out into the world) instead of choosing the chest, which is a valid inventory

**DOUBLE EDIT**

Putting extra redstone blocks in my fuel insertion chest (connected via shifter / pipe, shown in the photo above), the extra redstone goes to the (full) ElectroExtractor and is then basically lost. MergeItemStack issue?

**Comment by asiekierka** [comment]
This system is *not* smart routed! It's more like BuildCraft in the sense that items will just fly all over the place if you don't provide sufficient airflow.

Items always prefer to go straight, though I am considering making pipes act like insertion pipes by default. On a crossroads, items will go at random - try providing airflow at the bottom to route all items into the chest.

As for the rest, I need to research it.

**Comment by oitsjustjose** [comment]
Ah, alright, I don't know why I thought they were smart routed! I'll just use Hoppers to adapt for some of this then, and use Charset Pipes more for long-distance transportation!

**Comment by nabijaczleweli** [comment]
Don't take breaks, code 'til your eyes bleed! <sub*Yay!*</sub>

**Comment by asiekierka** [comment]
@oitsjustjose Long-distance is better suited for carts. Eh. I'm trying to design a good pipe system without smart routing... Insertion capabilities might do it, as you can always override with shifters.

**Comment by asiekierka** [comment]
All of the issues here should be fixed now.
