### ISSUE TITLE
Barrel texture has partially gone in Charset 0.5.6.0

### ISSUE THREAD

**Issue by 3TUSK** [asiekierka/CharsetMC#407]
![2019-07-20_15 45 06](https://user-images.githubusercontent.com/9113033/61584938-5f166480-ab05-11e9-8e12-72e8d20a3a86.png)

[insert crabrave music]
🦀 *barrel texture has gone* 🦀

**Comment by asiekierka** [comment]
what is this wood

**Comment by asiekierka** [comment]
:thinking:

**Comment by 3TUSK** [comment]
Oak wood barrels takes majority of them, however there are also birch, spruce, jungle, acacia and dark oak wood barrels.

**Comment by WenXin20** [comment]
I have the same problem, all barrels are missing their texture, both when placed on the ground, as an item, and in JEI.
