### ISSUE TITLE
Very weird server crash 

### ISSUE THREAD

**Issue by skyem123** [asiekierka/CharsetMC#409]
I'm not sure if this is specifically to do with charset, but after asking on IRC asie told me to report it here just in case.

So this started happening after we updated a bunch of mods which were project red and charset and a gravestone mod and autoreglib.

The error the server crashes with (very intermittently) does not mention any mod at all, and seems to be coming from a piston. We don't have many pistons and the one we did in the loaded chunks wasn't activated.

Something notable about the error is `java.lang.NoSuchMethodError: net.minecraft.block.state.IBlockState.fync_177230_c()` as it appears to be a tyop with fync instead of func.

Here's the crash log https://cdn.discordapp.com/attachments/601000111690219530/603528499466338305/crash-2019-07-23_23.45.50-server.txt

**Comment by skyem123** [comment]
As requested we removed charset patches from the server and so far the server hasn't crashed.

**Comment by asiekierka** [comment]
Fixed.
