### ISSUE TITLE
Registered ore dictionary entry of "ore" causes material heuristics crash

### ISSUE THREAD

**Issue by noobanidus** [asiekierka/CharsetMC#414]
[Here's](https://paste.dimdev.org/raboliyafe.mccrash) the crash log. I've yet to track down exactly what it is that's adding the weird ore dictionary name, but I'm presuming based on the error that it is simply "ore".

**Comment by noobanidus** [comment]
This seems to be caused by the most recent version of [NetherEx](https://github.com/LogicTechCorp/NetherEx/issues/176) which registers a number of items as "ore". While I personally feel that this isn't a very descriptive name and is most likely to cause conflict and confusion in the future, I think also that Charset relying on anything starting with "ore" to be more than just "ore" is a mistake that should be rectified.

**Comment by noobanidus** [comment]
This has been solved (i.e., conflict resolved) on NetherEx's end (file is uploading and awaiting approval), but looking further at the code there definitely seems sensible for there to be some sort of test of the size of the remainder of the string before attempting to index it, especially when it could result in a crash, so I'm leaving this ticket open.

**Comment by asiekierka** [comment]
That is correct.
