### ISSUE TITLE
Charset Lib Crash

### ISSUE THREAD

**Issue by WenXin20** [asiekierka/CharsetMC#415]
Minecraft v1.12.2
Forge v14.23.5.2838
Charset Lib v0.5.6.3
Charset Barrels v0.5.6.3
Charset Chests v0.5.6.0
Charset Immersion v0.5.6.0

I got this crash while loading the game, not sure what causes it though.
[Crash Report](https://paste.dimdev.org/oqahivujij.mccrash)

**Comment by noobanidus** [comment]
Appears to be the same as #414 Do you have the latest NetherEx installed?

**Comment by WenXin20** [comment]
Yes

**Comment by asiekierka** [comment]
Duplicate of #414.
