### ISSUE TITLE
Suggestion : Cable plugs

### ISSUE THREAD

**Issue by big-lip-bob** [asiekierka/CharsetMC#418]
I need to but a bundled cable just to prevent the redstone wire to not touch the insulated red one, since insulated wires can't power blocks their on im forced to use the exposed red wire this isolate it with the bundled, this makes me sad, time for cable plugs
![image](https://user-images.githubusercontent.com/41026257/62803803-bb104f80-baeb-11e9-9c9b-fd85f0c49c71.png)

**Comment by asiekierka** [comment]
Why not use Chisels & Bits to separate them?

**Comment by big-lip-bob** [comment]
Chisel and bits no good, Little Tiles good but not compatible with Multipart yet.

**Comment by big-lip-bob** [comment]
![image](https://user-images.githubusercontent.com/41026257/62819519-a1f0b880-bb56-11e9-968c-18263faeb9e0.png)
this makes me feel bad

**Comment by asiekierka** [comment]
>Chisel and bits no good

We have differing opinions here, unfortunately, and I'm not going to add a feature which I feel is solved much better by that mod.

**Comment by big-lip-bob** [comment]
well i'll look into alternatives, or ocntinue making such horrible circuits x), thanks anyway
