### ISSUE TITLE
Timer weird mecanics

### ISSUE THREAD

**Issue by big-lip-bob** [asiekierka/CharsetMC#419]
![image](https://user-images.githubusercontent.com/41026257/62812099-a42a2700-bb04-11e9-9bb9-2e1a2ffe9386.png)
am i missing out on something or is this intended

**Comment by asiekierka** [comment]
Notice that two of the outputs are disabled.

**Comment by big-lip-bob** [comment]
Yea but why and how is that, i mean i kinda want them

**Comment by big-lip-bob** [comment]
![image](https://user-images.githubusercontent.com/41026257/62820346-33662780-bb63-11e9-9219-78ccf38721af.png)
doing this fixes it but why does it disables itself or am i doing something again wrong
