### ISSUE TITLE
[0.2.1] Server crashing on startup

### ISSUE THREAD

**Issue by iarspider** [asiekierka/CharsetMC#43]
Crash log: http://paste.ubuntu.com/14666083/
Forge 1715, Charset 0.2.1

**Comment by GirafiStudios** [comment]
As it says in the changelog for Charset 0.2.0, if you're using TIS-3D you need to be using 0.8.3, or newer.

**Comment by iarspider** [comment]
... which isn't out yet. OK.

**Comment by GirafiStudios** [comment]
It's out as a dev build on: http://ci.cil.li/view/TIS-3D/job/TIS-3D-MC1.8.9/
