### ISSUE TITLE
Charset Locks conflict with Atum

### ISSUE THREAD

**Issue by Spiderfoxtail** [asiekierka/CharsetMC#433]
Hello, my players on my server have just discovered a bug when placing down the Atum Spinner wheel. Their clients were crashing when placing or trying to interact with this block. I read through the crash reports, but it said that Charset locks was what actually crashed. We were confused as no one has yet built a charset lock in world. I created a single player with Atum first, and then added Charset lib and charset locks and immediately recreated the crash when trying to interact with the Atum block. Here is my crash report from that test session.

[crash-2019-10-25_22.59.23-client.txt](https://github.com/CharsetMC/Charset/files/3774450/crash-2019-10-25_22.59.23-client.txt)

Please let me know if you need any more information regarding this bug.

**Comment by asiekierka** [comment]
Not sure if this is a bug on my side, but with 1.12.2 entering maintenance mode, now's not the time to check.
