### ISSUE TITLE
A few questions about the Charset Project 

### ISSUE THREAD

**Issue by ghost** [asiekierka/CharsetMC#435]
(Question 1) If the Charset is going to have some bits and pieces from Factorization, is it going to have the following Blocks/Features?
1. Ore Processing Feature 
2. Slag Furnace
3. Crystallizer
4. Mixer
5. Lacerator
6. Furnace Heater

(Question 2) When it’s time to move to 1.14 and above which mod loader are you going to use?
1. Forge(Be this one)
2. Fabric

**Comment by asiekierka** [comment]
(Question 1) (Question 2) Charset is currently in bugfix-only mode. There are no plans for any of my mods to move to 1.14 at this time.

However, I can say with high confidence that, as the creator of Fabric and the person behind many of its key principles, I'm not likely to pick Forge as my mod loader of choice.

If I decide to work on Charset again, it will most likely be as a new mod altogether - and yes, I do wish to bring more of Factorization's features back, although not necessarily as direct ports.
