### ISSUE TITLE
Charset chests don't output comparator values

### ISSUE THREAD

**Issue by democat3457** [asiekierka/CharsetMC#446]
Charset Lib 0.5.6.4
Charset Storage Chests 0.5.6.0

https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/issues/390

Could be caused by this line because the `Math.min` method returns an `int`, creating integer division that should always add 0 to `value`.
https://github.com/CharsetMC/Charset/blob/1.12-stable/src/main/java/pl/asie/charset/lib/utils/redstone/RedstoneUtils.java#L63

**Comment by asiekierka** [comment]
Fixed in 0.5.6.5. I am mostly retired from Minecraft modding, but with your diagnosis of the problem (and IntelliJ adding a warning for it, I suppose), the fix was trivial. Thank you!
