### ISSUE TITLE
[Storage - Chests][Suggestion] Add LootTable support

### ISSUE THREAD

**Issue by DoctorGallus** [asiekierka/CharsetMC#447]
Add LootTable support to charset chests, including a config option to spawn loot-chests using charset chests instead of the vanilla ones.

This would allow charset chests to fully replace the vanilla chests in the game.
It already partially replaces vanilla chests (crafting), but some are still left as part of world-generation, mainly as loot-chests. This results in a mix of available chests in-game, with the "less powerful" ones (vanilla) being uncraftable, which results in a weird and inconsistent situation.

PS: Really like your mods, looking forward to see what'll come next

**Comment by Foreck1** [comment]
I really wish someone would come back to this and make it a reality with a fork. I wanted to use these chests in custom structures and I didn't know that they didn't support loot tables. I was stuck for a year thinking I was writing the commands wrongly.
