### ISSUE TITLE
[Charset Storage - Chests] Item Destruction on Chest Explosion

### ISSUE THREAD

**Issue by waterpasta** [asiekierka/CharsetMC#452]
I had 4 chests, and they were blown up by a creeper. 1 chest dropped as an item, and the other 3 were destroyed. Only a few items, which I assume were in the chest that dropped as an item, were on the ground. I'm running the as-of-writing latest 1.12.2 versions of the lib and module.

**Comment by joe-vettek** [comment]
The package downloaded from the author's personal website does not have a chest module, which is puzzling. . . .

**Comment by democat3457** [comment]
> The package downloaded from the author's personal website does not have a chest module, which is puzzling. . . .

https://www.curseforge.com/minecraft/mc-mods/charset-storage-chests

**Comment by asiekierka** [comment]
It does, you just need to enable testing/experimental modules in the config. It's really unintuitive and a bad decision I made years ago, sorry.
