### ISSUE TITLE
Shifters ignoring ISidedInventory

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#46]
I haven't changed **any** of my code in CrissCross regarding the new Capabilities set, but ISided shouldn't still be ignored if you ask me - lots of mods will take quite a while to implement Capabilities I'd bet. Any chance you can continue to support both of them simultaneously? I'm going to work CrissCross onto the Capabilities API now.

**Comment by asiekierka** [comment]
I'm pretty sure I coded them in a manner which makes ISidedInventory not
ignored. Could you give me a test case?

2016-01-26 15:30 GMT+01:00 oitsjustjose <notifications@github.com>:

**Comment by oitsjustjose** [comment]
[Here you go](http://gfycat.com/OpenWebbedIbex) - this doesn't happen with Vanilla Furnaces, but happens with my Tiles and the Evolved Furnace from the Alt-F4 Mod.

**Comment by oitsjustjose** [comment]
Okay - it's not your fault, this interaction also occurs with Vanilla Hoppers. I guess Forge needs to be the one still considering ISidedness? Regardless, I've already added Capabilities abilities to CrissCross, so it's good to go. Closing this because it isn't your fault :)

**Comment by asiekierka** [comment]
I added code to explicitly support ISidedInventories. If they are not being
supported it's well my fault.

2016-01-26 22:18 GMT+01:00 oitsjustjose <notifications@github.com>:

**Comment by oitsjustjose** [comment]
Oh. 
Kthen.

**Comment by asiekierka** [comment]
Probably won't matter much on 1.9.
