### ISSUE TITLE
Wire MultiPart Crash

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#48]
[Crashlog](http://paste.asie.pl/F8Ef)

The crash occurred when placing a wire down alongside a chiseled bit: when the wire in the bit had to change its shape to connect to adjacent wire, this crash occurs, but after reloading the world, everything works as expected (including the wire connection at both endpoints)

**Comment by asiekierka** [comment]
Sounds like an MCMultiPart bug.
