### ISSUE TITLE
[Suggestion] Redstone Interaction for Shifters

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#5]
Quick and easy one (I hope, at least):

![2015-12-02_14 51 55](https://cloud.githubusercontent.com/assets/3887324/11542347/fa09e8f2-9904-11e5-9a25-334f87cc371b.png)

Can we make this work? Or is there a reason that it doesn't? Thought it'd be cool, I don't like levers >:C

**Comment by asiekierka** [comment]
That's not a suggestion, that's a bug related to not porting over redstone
behaviour to 1.8 correctly.

2015-12-02 20:57 GMT+01:00 oitsjustjose <notifications@github.com>:

**Comment by oitsjustjose** [comment]
Heh. Whoops. I thought you just specifically liked levers more :P
