### ISSUE TITLE
crash on server whe  using redstone wire with neotech energy pipe to stop signal

### ISSUE THREAD

**Issue by SDUBZ** [asiekierka/CharsetMC#51]
description explains it heres the crash http://pastebin.com/Hwt4jE8u

**Comment by asiekierka** [comment]
Looks like a NeoTech bug to me, report to them please.

2016-02-20 12:50 GMT+01:00 SDUBZ <notifications@github.com>:

**Comment by SDUBZ** [comment]
i did report to you and him :D
