### ISSUE TITLE
Crash after placing "+" redstone cable

### ISSUE THREAD

**Issue by justin-ermer** [asiekierka/CharsetMC#52]
Initially placing it alongside a neotech basic rf storage -> neotech electric furnace caused a server and client crash, with client log http://pastebin.com/BMcAmvV4 and server log http://pastebin.com/0XzfBCJE . 

Placing a wire again alongside Actually Additions Crusher results in only server crash with the log http://pastebin.com/08ivQpVC.

**Comment by justin-ermer** [comment]
The server crashes when cables are broken or the block they're attached to are broken.

client log from latest server disconnects from these cables http://pastebin.com/TMsGiWVB

**Comment by asiekierka** [comment]
The paste is no longer available.

**Comment by asiekierka** [comment]
Should be fixed with the next release, please check and re-open if necessary.
