### ISSUE TITLE
XOR gate (and possible others) not updating properly

### ISSUE THREAD

**Issue by williewillus** [asiekierka/CharsetMC#55]
0.2.3

Steps to reproduce:
1. Place down XOR gate with output facing away from you
2. Place wire on all four sides of it
3. Powering left or right will work as intended.
4. Now, take out the left and right wires and power the gate directly on both sides with a RS torch. Upon removing the torches the gate will not update its state.

**Comment by Xiaminou** [comment]
same problem with 0.2.4:
![2016-03-16_17 41 22](https://cloud.githubusercontent.com/assets/8670392/13820591/5f2ada20-eb9e-11e5-8b67-eb5baa4ce0df.png)
