### ISSUE TITLE
CME from PacketItemUpdate in charset pipes

### ISSUE THREAD

**Issue by darkevilmac** [asiekierka/CharsetMC#59]
MC Version: 1.8.9
Charset Version: 0.2.4

Occurs on login, just a guess but you might need to submit the packet to the main thread if that's not already happening. If it's already been fixed on the latest version I apologize, just didn't see it in the changelog.

http://pastebin.com/z24rVHHK

**Comment by asiekierka** [comment]
Fixed in 1.9, technically 1.8.9 is abandoned but I'm going to fix it in a sec...

**Comment by asiekierka** [comment]
Fixed for 1.9 in https://github.com/asiekierka/CharsetMC/commit/18f4b409d38c8091ef17d3dbc183e39a81193dea
