### ISSUE TITLE
Crash NPE in onPlayerDeath?

### ISSUE THREAD

**Issue by Inari-Whitebear** [asiekierka/CharsetMC#61]
Well, not much to say....
https://gist.github.com/Inari-Whitebear/74202fed8f96385ecc4ac3614eac3414

**Comment by Saytiras** [comment]
Yep, happens in my world as well. But it doesn't happen every time someone dies on the server. Thought at first that the problem was with Abyssalcraft mobs because I was killed by one when the crash occured. But death through fall damage crashed the server too :/

Forge: 12.16.1.1901 (1.9)

**Comment by Inari-Whitebear** [comment]
Also happened when a normal Zombie killed me :s
