### ISSUE TITLE
GUI orientation after pipes rendering items

### ISSUE THREAD

**Issue by ruyanve** [asiekierka/CharsetMC#64]
Hey Asie,

don't know what happened here but every time a pipe renders an item my GUI goes haywire (and stays until reloading the world)...

http://i.imgur.com/kLf0Zm3.jpg

It's only the orientation tho, the textures look fine ingame, don't know what happened with the screen capture, sorry.

Using:
Forge 1909
charset-0.3.0-pre5-pipes.jar
MCMultiPart-experimental-1.2.0_68-universal.jar  

On a GTX960

Also... why are the wires called cables ingame? Consistency ;-)

**Comment by asiekierka** [comment]
Because they're not wires. A "redstone wire" is that dust-like thing you spray on floors to get them to conduct signals. You know, redstone.

As for the bug, I'm aware of it, but I can't in any way get it to reproduce - HOWEVER, I am attempting a fix.

**Comment by asiekierka** [comment]
Please try http://asie.pl/Charset-0.3.0-test-i64.jar

**Comment by ruyanve** [comment]
Works like a charm, window mode and full screen. You da best!

And about the cables, err wires, err things... I'm just asking because...
*cough*
+ (Wires - (0.0.3+) [MCMP] Redstone wires (beta)) 
*cough*
Consistency Asie! ;-D

**Comment by asiekierka** [comment]
Oh, *that* consistency. I'll probably rename the module to CharsetWiring and change the description - but *that* site is outdated!

**Comment by ruyanve** [comment]
You can call them Danks for all I care ;-)
Keep it up and thanks again for the quick fix!
