### ISSUE TITLE
[1.9.4 pre5]Extracting items from a chest with pipes causes a major graphical glitch

### ISSUE THREAD

**Issue by jawsawn** [asiekierka/CharsetMC#69]
it seems to be reseting my screen size or something. It is really odd. using the latest forge and charset 1.9.4 pre5. 

https://gyazo.com/12199e73df3dca7fd09c8390b83d9943

Steps to Reproduce:
1-Put down a chest
2-Put a shifter and pipes 
3-Put some items in the chest (doesnt matter the type)
3-Activate the shifter by giving a redstone signal

The graphical glitch fixes when you log out and log back in.

Also its mostly caused because of the items "in" the pipes, if you have a looping pipes and you log off and log back with the items in the pipes it keeps happening.

**Comment by jawsawn** [comment]
also lucky issue number :p

**Comment by asiekierka** [comment]
fixed in pre6
