### ISSUE TITLE
Wires not receiving power through solid blocks

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#7]
I'd understand if this was unintended, but I didn't know if it was or not ;)

![2015-12-06_12 55 28](https://cloud.githubusercontent.com/assets/3887324/11614972/044a3b02-9c19-11e5-84f8-96bf5ed2c5c6.png)

**Comment by asiekierka** [comment]
Not intended.

**Comment by asiekierka** [comment]
https://github.com/asiekierka/CharsetMC/commit/7c119924a23452c604349fe81bb01ee8bed7c17b
