### ISSUE TITLE
Barrels are weird

### ISSUE THREAD

**Issue by Darkhax** [asiekierka/CharsetMC#72]
When searching in JEI the barrel and related upgrades can not be found. The barrel card does show however. You can also access the barrel crafting recipe by searching for uses of a log or a slab.

Barrels also lose their type when broken. If you craft a willow barrel and break it you will get an oak barrel. 

This is with Charset 1.9.4-0.3.0-Pre7

**Comment by asiekierka** [comment]
https://github.com/CharsetMC/Charset/commit/95efbc3f8ae1003d3a8f3cb8325b2506581736ee for the second one; could not reproduce the JEI issue, perhaps I fixed it already?
