### ISSUE TITLE
Fluid pipes can only be filled with redstone signal

### ISSUE THREAD

**Issue by rubensworks** [asiekierka/CharsetMC#73]
![2016-06-10_20 56 07](https://cloud.githubusercontent.com/assets/440384/15975512/1a4c8338-2f4e-11e6-9e9a-6fbf2276f23d.png)

The tank in this screenshot auto-exports fluids to the bottom, but the charset pipes only seem to accept fluids when it has an active redstone signal. So enabling the lever on the left makes everything flow.

**Comment by asiekierka** [comment]
Yes. That is a limitation of the current flow algorithm. Fluids are hard.

2016-06-10 20:59 GMT+02:00 Ruben Taelman notifications@github.com:
