### ISSUE TITLE
Can't craft crates in 1.8.9 version

### ISSUE THREAD

**Issue by ozBillo** [asiekierka/CharsetMC#74]
Can't craft crates. What is the recipe?
Using version 0.2.6 for Minecraft 1.8.9 from charset.asie.pl download page.

**Comment by asiekierka** [comment]
Crates are not finished in any version of Charset, and even if/when they
are they will be exclusive to 0.3.0+.

2016-06-11 8:48 GMT+02:00 ozBillo notifications@github.com:
