### ISSUE TITLE
Request: Config option to disable backpack using chest item slot

### ISSUE THREAD

**Issue by wise-io** [asiekierka/CharsetMC#75]
I love the backpack, but I hate that it takes the chest armor slot, preventing me from using a complete armor set. Can you add an option to the config to allow equipping a backpack without using up the chest slot?

**Comment by asiekierka** [comment]
I'm afraid it would require a lot of additional code, more than I'm willing to work on for now. Maybe in the faraway future.

**Comment by asiekierka** [comment]
No longer relevant, backpacks removed. Try copygirl's WearableBackpacks.
