### ISSUE TITLE
The dialog of the tape drive for uploading audio totally freezes MC until the dialog is closed

### ISSUE THREAD

**Issue by Rukachan** [asiekierka/CharsetMC#77]
Tried it on Debian GNU/Linux with OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-2-b14), Charset 1.9.4-0.3.0-pre10 and forge 1.9.4-12.17.0.1964.

**Comment by asiekierka** [comment]
Fixed in 0.3.1 (as well as Vazkii's fork).
