### ISSUE TITLE
Implement crazypants.enderio.api.redstone.IRedstoneConnectable

### ISSUE THREAD

**Issue by Rukachan** [asiekierka/CharsetMC#78]
See https://github.com/SleepyTrousers/EnderIO/blob/1.9/src/main/java/crazypants/enderio/api/redstone/IRedstoneConnectable.java

**Comment by asiekierka** [comment]
Is it a capability?

**Comment by Rukachan** [comment]
No

**Comment by asiekierka** [comment]
Impossible to implement for technical reasons

**Comment by Rukachan** [comment]
Just in case anyone in the future stumbles upon this bug report and wonders what the reasons making it impossible are: as asie said in the irc "multiparts cannot implement any APIs which are not capabilities".
