### ISSUE TITLE
[1.9.4] No class found error

### ISSUE THREAD

**Issue by Sunconure11** [asiekierka/CharsetMC#79]
http://pastebin.com/e4ZLrtCS

Couldn't use the wires due to the fact that multipart is not on 1.9.4, only 1.9.

**Comment by asiekierka** [comment]
Check the dependencies list when downloading Charset. The setup you have
used requires MCMultiPart, which is listed there.

MCMultiPart for 1.9.4 is not officially released and there is nothing I can do about it. You can find it if you dig around, or compile from source.

2016-06-16 20:27 GMT+02:00 Absinthe notifications@github.com:

**Comment by Sunconure11** [comment]
Guess I'll wait then.
