### ISSUE TITLE
[1.10] Crash when breaking charset pipes

### ISSUE THREAD

**Issue by mezz** [asiekierka/CharsetMC#81]
https://gist.github.com/mezz/465b07c07368517294f2f59d829e2e7e
I used a tinker's pick to break some charset pipes (the purple item ones) and crashed.

**Comment by GirafiStudios** [comment]
Vazkii maintains Charset for 1.10 and above, on this branch: https://github.com/Vazkii/Charset :)
Although I think this crash is caused by MC Multipart, as mentioned in the changelog for the latest version: http://minecraft.curseforge.com/projects/mcmultipart/files/2310444

**Comment by mezz** [comment]
Hm I don't think there was an issue tracker open there last time I looked. Thanks for the info.

**Comment by GirafiStudios** [comment]
Yeah there were no issue tracker for the first day or two :)
