### ISSUE TITLE
missing mod info in mcmod.info

### ISSUE THREAD

**Issue by scootz** [asiekierka/CharsetMC#82]
Noticed CharsetCarts and CharsetFarming module info is missing from mcmod.info. Is this intentional?

**Comment by asiekierka** [comment]
mcmod.info is generated from modules.json using the genmcmod.js script. If a module is not finished, it's not listed in modules.json (as that's the file read by the download interface), so it's not listed in mcmod.info or packaged in any release JAR. Yes, it is intentional.
