### ISSUE TITLE
Using note block crashes server

### ISSUE THREAD

**Issue by glynie** [asiekierka/CharsetMC#88]
Using a note block (playing a note) in FTB Infinity Lite 1.10.2 crashes the server.
Problem does not apply to single player.

Server bug report: https://paste.ubuntu.com/23542409/

**Comment by asiekierka** [comment]
Tell the FTB folk to update to 0.3.1+, where it has convienently been fixed.

(They might have some problems, though, seeing as some modules have been dropped. Tell them to replace Storage.Backpacks with WearableBackpacks and gates with SCM, as for wires... no replacement exists ATM.)
