### ISSUE TITLE
[Suggestion] Powered Pipes

### ISSUE THREAD

**Issue by Lathanael** [asiekierka/CharsetMC#89]
A new pipe which can be powered by some means (FU maybe?) which accelerate Items traveling from one end to the other of the powered pipes. The longer the traveled distance the more power is used to accelerate the items.
Powered pipes can not be placed such that an intersection is formed, i.e. no routing just one way travel.
Basicly a pipe like the RP2 Magtube. Imo it fits with the basic nature of the pipes.

**Comment by asiekierka** [comment]
I can see that the pipes can be a bit slow for some right now, however:

* The reason pipes cannot currently be accelerated is that my plan was to set them to a single, predictable speed, letting you somehow (eventually?) time your designs in relation to the speed of the pipe's movement. However, this idea will be verified in the future, and I might come back to the idea of some kind of acceleration system shall a design need for one arise.
* If Charset decides to use a power system, it will probably be custom and not compatible with RF/Tesla/FU.
* I believe having more than one pipe would set a negative precedent against the simplicity/intuitiveness of the mod's pipes, which are their main design goal. Sorry.
* **EDIT:** Long-distance travel is better achieved with carts (Railcraft?) than pipes.

As always, if you disagree, feel free to make an addon and/or a fork of the specific module - then you can just tell people to use your module in place of the official one, but still depend on Lib etc.

**Comment by Lathanael** [comment]
:( For long distance travel carts are better, i agree. I had base-wide travel in mind, like 10 to 50 blocks especially vertically which is a pain to setup with carts(even with railcraft) and most often looking ugly.
But i can understand your point so i guess i'll have to look into how to make addon pipes if i ever find the time. Thanks for the elaborate response!
