### ISSUE TITLE
Crash when placing free-standing wire adjacent to Redstone Dust

### ISSUE THREAD

**Issue by oitsjustjose** [asiekierka/CharsetMC#9]
Just put down a free-standing wire next to redstone dust.. [and then this happened](http://paste.ee/p/dqJVs)

Sorry! :P

**Comment by asiekierka** [comment]
>redstone dust passing null through canConnectRedstone

!@#$%

**Comment by asiekierka** [comment]
https://github.com/asiekierka/CharsetMC/commit/7c119924a23452c604349fe81bb01ee8bed7c17b
