### ISSUE TITLE
Idea: Integrated in-pipe Shifters

### ISSUE THREAD

**Issue by ToadsworthLP** [asiekierka/CharsetMC#90]
So, during the long period of you trying to forget your love to Minecraft, I got some ideas to improve Charset Pipes. Here's the first:
Integrated Shifer: Attach a shifter to the center of a pipe to make smaller systems possible and use a wrench to set the direction it "shifts" to. Here's a picture:
![integrated-shifter](https://cloud.githubusercontent.com/assets/17457177/20865180/9027b65c-ba0b-11e6-9830-641543e4d5eb.png)
It should be able to suck in items from containers from the top and the left side (in this case) and would also work like the BC iron pipe. Like the shifter, it needs a redstone signal to work. This should be craftable by shapelessly putting a pipe and a shifter inside the crafting grid.

**Comment by ToadsworthLP** [comment]
I don't know if it would work, but it may look good to just use the normal pipe texture and put a smaller version of the standard shifter model over the crossing, which would make it look more 3D-y

**Comment by asiekierka** [comment]
Hello, Donald.

Sorry, no. This idea was suggested countless times, but my goal with Charset is explicitly *not* designing with miniaturization in mind. Sorry.
