### ISSUE TITLE
NPE When Right-Clicking Barrel In SP

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#91]
Kicked out of singleplayer world to the multiplayer server list when right-clicking an empty barrel with an empty hand.

**Mod version:** 0.4.0-pre1
**Forge version:** [1.11-13.19.1.2188](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2188/forge-1.11-13.19.1.2188-changelog.txt)

**Stacktrace:** [gist/bokiwudepu](https://gist.github.com/InsomniaKitten/40bba0458ca15b3a0a10efc6d88b0f04) - previously hastebin

---

**EDIT:** Performing the same action on a barrel cart caused a crash to desktop.
**Crash report:** [gist/crash-2016-12-11_19.24.40-client](https://gist.github.com/InsomniaKitten/98cf8a94c57288b83af93f9537c150a7)

**Comment by asiekierka** [comment]
Caused by Forge 2185+ (fix: https://github.com/asiekierka/MinecraftForge/commit/84675cb61a3d05d659c7fcbed7dca5fbfdfbd263). A workaround has been implemented in https://github.com/CharsetMC/Charset/commit/8fdc623f502c87124ea722f0822e80d5f61fc8b2.
