### ISSUE TITLE
Crash During Game Initialisation

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#92]
Game crashes to desktop with an NPE during initialisation.

**Mod version:** 0.4.0-pre1
**Forge version:** [1.11-13.19.1.2188](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2188/forge-1.11-13.19.1.2188-changelog.txt)

**Crash report:** [gist/crash-2016-12-11_20.56.23-client](https://gist.github.com/InsomniaKitten/bb7aab5978d687d956f28d06109b622b)

---

I disabled OptiFine and now a new crash is occurring.
**Crash report 2:** [gist/crash-2016-12-11_21.06.38-client](https://gist.github.com/InsomniaKitten/0e4bae7af7a6fba5216056231d362a6c)

I can also confirm that this crash still occurs with FoamFix disabled.
I wasn't sure if that could cause any potential issues in this case.

---

**The original crash with OptiFine installed happened out of the blue. I went for food, came back, launched the game, and it started crashing. I have yet to figure out why it randomly decided to misbehave but I'm looking into it.**

**Comment by asiekierka** [comment]
The second crash was already fixed in 0.4.0-pre2 (to be released), and the first crash is... odd, but familiar and possibly related to OptiFine.

No need to test without FoamFix for this project, by the way. :)
