### ISSUE TITLE
Locked Inventories Can Be Moved - Storage Module

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#93]
### Versions:

**Mod version:** Built from source, latest commit: https://github.com/CharsetMC/Charset/commit/8be6262e3f789092313d7f5ee1a5577e4912db86 - [view](https://github.com/CharsetMC/Charset/tree/8be6262e3f789092313d7f5ee1a5577e4912db86)
**Forge version:** [1.11-13.19.1.2188](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2188/forge-1.11-13.19.1.2188-changelog.txt)

### Details:
**Locked chests can be picked up by [Chest Transporters](https://minecraft.curseforge.com/projects/chest-transporter), and presumably other chest moving tools.**
Circumvents the prevention of inventory access, allowing a player to pick up a locked chest and replace it elsewhere, leaving the lock entity behind in it's original location.

###### Reported here as I am not sure if you would want to just do a workaround for it, or report it to other mods to prevent their tools from moving locked inventories.

**Comment by asiekierka** [comment]
Ideally, they should emit a BlockBreakEvent.
