### ISSUE TITLE
Locks Issue With Double Chests - Storage Module

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#94]
### Versions:

**Mod version:** Built from source, latest commit: https://github.com/CharsetMC/Charset/commit/8be6262e3f789092313d7f5ee1a5577e4912db86 - [view](https://github.com/CharsetMC/Charset/tree/8be6262e3f789092313d7f5ee1a5577e4912db86)
**Forge version:** [1.11-13.19.1.2188](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2188/forge-1.11-13.19.1.2188-changelog.txt)

### Details:
**Double chests drop items on the half with no lock entity.**
The end of a double chest that doesn't contain the lock entity is breakable, and will drop it's contents when broken by a player. Break event needs to be cancelled for adjacent inventories affected by the lock system.

**Comment by asiekierka** [comment]
Fixed in 0.4.2-pre1
