### ISSUE TITLE
Server Crash - java.lang.NullPointerException: Ticking player at pl.asie.charset.tweaks.shard.TweakGlassShards.onBlockHarvest

### ISSUE THREAD

**Issue by ProsperCraft** [asiekierka/CharsetMC#97]
https://gist.github.com/ProsperCraft/6085ab842a8ab4ed9b618991510fb4b1

This happened on my multiplayer server.

**Comment by asiekierka** [comment]
1. Please check with the latest Charset version as per http://charset.asie.pl/ next time. Vazkii's fork is *generally* not going to be supported going forward.
2. The block your player tried to mine overrides getDrops() in a way which returns null, which is against the method's original behaviour as defined in net.minecraft.block.Block. In other words, the blame lies on the mod which provides said block, which has sadly not been logged - but is definitely not vanilla or Forge.

Despite all that, I am going to add a safeguard for this in Charset 0.3.3 - upgrading to it from Vazkii's fork might be tough, however, as some features have been silently dropped.
