### ISSUE TITLE
[OptiFine] Crash When Disabling Shaders

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/CharsetMC#99]
Game crashed to desktop when trying to turn off shaders in the options menu.

**Mod version:** Built from source, latest commit: https://github.com/CharsetMC/Charset/commit/8be6262e3f789092313d7f5ee1a5577e4912db86 - [view tree](https://github.com/CharsetMC/Charset/tree/8be6262e3f789092313d7f5ee1a5577e4912db86)
**Forge version:** [1.11-13.19.1.2189](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2189/forge-1.11-13.19.1.2189-changelog.txt)

**Crash report:** [hastebin/qetexucinu](https://hastebin.com/qetexucinu.txt)

**Comment by asiekierka** [comment]
Looks like an OptiFine issue to me, honestly. Closing until proven otherwise.
